apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  ports:
  - containerPort: 5
    hostIP: ACTOKEY
    hostPort: 1
    name: ACTOKEY
    protocol: ACTOKEY
  - containerPort: 5
    hostIP: ACTOKEY
    hostPort: 0
    name: null
    protocol: ACTOKEY
  - containerPort: 3
    hostIP: ACTOKEY
    hostPort: null
    name: null
    protocol: ACTOKEY
  probes: {}
  replicas: 3
  storageType: persistence
