apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  probes:
    livenessProbe:
      failureThreshold: 2
      initialDelaySeconds: 3
      periodSeconds: 2
      successThreshold: 3
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: null
      initialDelaySeconds: 5
      periodSeconds: 0
      successThreshold: 1
      timeoutSeconds: 2
  replicas: 3
  storageType: persistence
