apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: test-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: true
    env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: null
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 3
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: .8E+9437.
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: null
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: null
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 4
          resource: ACTOKEY
        secretKeyRef: null
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: null
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 4
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
