apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      sidecars:
      - args:
        - ACTOKEY
        - ACTOKEY
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        env: []
        envFrom:
        - configMapRef:
            name: null
            optional: true
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: true
        - configMapRef:
            name: ACTOKEY
            optional: true
          prefix: null
          secretRef: null
        - configMapRef:
            name: ACTOKEY
            optional: null
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: false
        - configMapRef:
            name: ACTOKEY
            optional: true
          prefix: ACTOKEY
          secretRef:
            name: null
            optional: false
        - configMapRef:
            name: ACTOKEY
            optional: null
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: false
        image: ACTOKEY
        imagePullPolicy: null
        lifecycle:
          postStart:
            exec: null
            httpGet:
              host: ACTOKEY
              httpHeaders:
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              path: ACTOKEY
              port: 5
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: 4
          preStop:
            exec:
              command:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            httpGet:
              host: ACTOKEY
              httpHeaders: null
              path: ACTOKEY
              port: 3
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: ACTOKEY
        livenessProbe:
          exec: null
          failureThreshold: 3
          grpc:
            port: 0
            service: ACTOKEY
          httpGet: null
          initialDelaySeconds: 2
          periodSeconds: 1
          successThreshold: 0
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 1
          timeoutSeconds: 2
        name: ACTOKEY
        ports:
        - containerPort: 2
          hostIP: ACTOKEY
          hostPort: 3
          name: ACTOKEY
          protocol: ACTOKEY
        readinessProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 2
          grpc:
            port: 4
            service: ACTOKEY
          httpGet: null
          initialDelaySeconds: 3
          periodSeconds: null
          successThreshold: 3
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 2
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 800m
            memory: 1000m
          requests:
            cpu: 800m
            memory: 1000m
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            drop:
            - ACTOKEY
          privileged: true
          procMount: ACTOKEY
          readOnlyRootFilesystem: false
          runAsGroup: 5
          runAsNonRoot: true
          runAsUser: 5
          seLinuxOptions:
            level: ACTOKEY
            role: ACTOKEY
            type: ACTOKEY
            user: ACTOKEY
          seccompProfile:
            localhostProfile: ACTOKEY
            type: ACTOKEY
          windowsOptions:
            gmsaCredentialSpec: ACTOKEY
            gmsaCredentialSpecName: null
            hostProcess: true
            runAsUserName: ACTOKEY
        startupProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 5
          grpc: null
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: null
            port: 3
            scheme: ACTOKEY
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 2
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 2
          timeoutSeconds: 0
        stdin: false
        stdinOnce: true
        terminationMessagePath: ACTOKEY
        terminationMessagePolicy: ACTOKEY
        tty: false
        volumeDevices: null
        volumeMounts:
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: false
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: false
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: null
          name: ACTOKEY
          readOnly: false
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        workingDir: ACTOKEY
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      priorityClassName: ''
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
