apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    serviceAccountName: ''
    size: 2
    storage:
      inMemory: {}
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      sidecars:
      - args: null
        command:
        - ACTOKEY
        env:
        - name: ACTOKEY
          value: null
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: true
            fieldRef: null
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: -.6702
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
            fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 4
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: null
              optional: false
            fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 1
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
        envFrom: null
        image: ACTOKEY
        imagePullPolicy: ACTOKEY
        lifecycle:
          postStart:
            exec:
              command:
              - ACTOKEY
              - ACTOKEY
            httpGet:
              host: ACTOKEY
              httpHeaders: null
              path: ACTOKEY
              port: ACTOKEY
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: ACTOKEY
          preStop:
            exec:
              command:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            httpGet:
              host: ACTOKEY
              httpHeaders: []
              path: ACTOKEY
              port: 5
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: 3
        livenessProbe:
          exec:
            command:
            - ACTOKEY
          failureThreshold: null
          grpc: null
          httpGet:
            host: ACTOKEY
            httpHeaders: []
            path: ACTOKEY
            port: 2
            scheme: ACTOKEY
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 3
          tcpSocket:
            host: ACTOKEY
            port: 4
          terminationGracePeriodSeconds: null
          timeoutSeconds: 4
        name: ACTOKEY
        ports:
        - containerPort: 2
          hostIP: ACTOKEY
          hostPort: 5
          name: null
          protocol: ACTOKEY
        - containerPort: 3
          hostIP: ACTOKEY
          hostPort: 3
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 1
          hostIP: ACTOKEY
          hostPort: 0
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 4
          hostIP: null
          hostPort: 0
          name: null
          protocol: ACTOKEY
        - containerPort: 5
          hostIP: ACTOKEY
          hostPort: 5
          name: ACTOKEY
          protocol: ACTOKEY
        readinessProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 1
          grpc:
            port: 1
            service: ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: ACTOKEY
            scheme: null
          initialDelaySeconds: 2
          periodSeconds: 1
          successThreshold: 3
          tcpSocket:
            host: ACTOKEY
            port: 4
          terminationGracePeriodSeconds: 4
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 800m
            memory: 1000m
          requests:
            cpu: 800m
            memory: 1000m
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            drop:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          privileged: true
          procMount: ACTOKEY
          readOnlyRootFilesystem: null
          runAsGroup: null
          runAsNonRoot: true
          runAsUser: 5
          seLinuxOptions:
            level: ACTOKEY
            role: ACTOKEY
            type: ACTOKEY
            user: null
          seccompProfile:
            localhostProfile: ACTOKEY
            type: ACTOKEY
          windowsOptions:
            gmsaCredentialSpec: ACTOKEY
            gmsaCredentialSpecName: ACTOKEY
            hostProcess: false
            runAsUserName: ACTOKEY
        startupProbe:
          exec:
            command: []
          failureThreshold: 2
          grpc:
            port: 2
            service: ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders: null
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          initialDelaySeconds: 3
          periodSeconds: 2
          successThreshold: null
          tcpSocket:
            host: ACTOKEY
            port: 1
          terminationGracePeriodSeconds: 2
          timeoutSeconds: 4
        stdin: true
        stdinOnce: true
        terminationMessagePath: ACTOKEY
        terminationMessagePolicy: ACTOKEY
        tty: true
        volumeDevices:
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        volumeMounts: null
        workingDir: ACTOKEY
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
