apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: test-cluster
spec:
  redis: {}
  sentinel:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - us-west-1
            topologyKey: failure-domain.beta.kubernetes.io/zone
          weight: 100
    customConfig:
    - down-after-milliseconds 2000
    - failover-timeout 3000
    imagePullPolicy: IfNotPresent
    replicas: 3
