apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: test-cluster
spec:
  clusterName: cluster1
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M
  managementApiAuth:
    insecure: {}
  serverType: cassandra
  serverVersion: 3.11.7
  size: 3
  storageConfig:
    additionalVolumes:
    - mountPath: ACTOKEY
      name: y
      pvcSpec:
        accessModes: ReadWriteOnce
        dataSource:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        dataSourceRef:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        resources:
          requests:
            storage: 1000m
        selector:
          matchExpressions:
          - key: ACTOKEY
            operator: ACTOKEY
            values: []
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values: null
          - key: ACTOKEY
            operator: ACTOKEY
            values: []
          matchLabels:
            ACTOKEY: ACTOKEY
        storageClassName: ACTOKEY
        volumeMode: ACTOKEY
        volumeName: ACTOKEY
    - mountPath: ACTOKEY
      name: w
      pvcSpec:
        accessModes: ReadWriteOnce
        dataSource:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        dataSourceRef:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        resources:
          requests:
            storage: 1000m
        selector:
          matchExpressions:
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values: []
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          matchLabels:
            ACTOKEY: ACTOKEY
        storageClassName: ACTOKEY
        volumeMode: ACTOKEY
        volumeName: ACTOKEY
    - mountPath: ACTOKEY
      name: '5'
      pvcSpec:
        accessModes: ReadWriteOnce
        dataSource:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        dataSourceRef: null
        resources:
          requests:
            storage: 1000m
        selector:
          matchExpressions:
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          matchLabels:
            ACTOKEY: ACTOKEY
        storageClassName: null
        volumeMode: ACTOKEY
        volumeName: ACTOKEY
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: server-storage
  tolerations: []
