apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: test-cluster
  namespace: knative-eventing
spec:
  config:
    config-kreference-mapping:
      key1: value1
  deployments:
  - env:
    - container: eventing-controller
      envVars:
      - name: ENVAR_1
        value: VALUE_1
    name: eventing-controller
    resources:
    - container: eventing-controller
      limits: {}
      requests:
        cpu: 300m
        memory: 100M
  podDisruptionBudgets:
  - minAvailable: 50%
    name: eventing-webhook
  registry:
    imagePullSecrets:
    - name: ACTOKEY
    - name: ACTOKEY
    - name: ACTOKEY
    - name: null
    - name: ACTOKEY
  services:
  - name: eventing-webhook
  version: 1.6.0
