apiVersion: pxc.percona.com/v1-11-0
kind: PerconaXtraDBCluster
metadata:
  finalizers:
  - delete-pxc-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.11.0-pxc8.0-backup
    imagePullPolicy: IfNotPresent
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    schedule:
    - keep: 3
      name: sat-night-backup
      schedule: 0 0 * * 6
      storageName: s3-us-west
    - keep: 5
      name: daily-backup
      schedule: 0 0 * * *
      storageName: fs-pvc
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6G
      s3-us-west:
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
        type: s3
        verifyTLS: true
  crVersion: 1.11.0
  enableCRValidationWebhook: true
  haproxy:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-haproxy
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 100M
  pmm:
    enabled: false
    image: percona/pmm-client:2.28.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 300m
        memory: 150M
    serverHost: monitoring-service
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: false
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    autoRecovery: true
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    imagePullPolicy: IfNotPresent
    livenessDelaySec: 300
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    sidecars:
    - args:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      command: []
      env: null
      envFrom:
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: true
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef: null
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: ACTOKEY
        secretRef:
          name: null
          optional: false
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          tcpSocket:
            host: null
            port: ACTOKEY
        preStop:
          exec:
            command: []
          httpGet:
            host: null
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: 3
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
      livenessProbe:
        exec:
          command: []
        failureThreshold: 5
        grpc:
          port: 4
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 1
        periodSeconds: 4
        successThreshold: 4
        tcpSocket: null
        terminationGracePeriodSeconds: 2
        timeoutSeconds: 4
      name: ACTOKEY
      ports: []
      readinessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 4
        grpc:
          port: 0
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 0
          scheme: ACTOKEY
        initialDelaySeconds: 0
        periodSeconds: 4
        successThreshold: 3
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        terminationGracePeriodSeconds: 5
        timeoutSeconds: 4
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          drop:
          - ACTOKEY
          - ACTOKEY
        privileged: true
        procMount: ACTOKEY
        readOnlyRootFilesystem: false
        runAsGroup: 3
        runAsNonRoot: false
        runAsUser: 1
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile:
          localhostProfile: ACTOKEY
          type: ACTOKEY
        windowsOptions:
          gmsaCredentialSpec: ACTOKEY
          gmsaCredentialSpecName: ACTOKEY
          hostProcess: false
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 2
        grpc: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 1
          scheme: ACTOKEY
        initialDelaySeconds: 0
        periodSeconds: 3
        successThreshold: 5
        tcpSocket:
          host: ACTOKEY
          port: 4
        terminationGracePeriodSeconds: 2
        timeoutSeconds: 5
      stdin: false
      stdinOnce: null
      terminationMessagePath: null
      terminationMessagePolicy: ACTOKEY
      tty: false
      volumeDevices:
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      volumeMounts:
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: true
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      workingDir: ACTOKEY
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 8.0-recommended
    schedule: 0 4 * * *
    versionServiceEndpoint: https://check.percona.com
