apiVersion: pxc.percona.com/v1-11-0
kind: PerconaXtraDBCluster
metadata:
  finalizers:
  - delete-pxc-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.11.0-pxc8.0-backup
    imagePullPolicy: IfNotPresent
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    schedule:
    - keep: 3
      name: sat-night-backup
      schedule: 0 0 * * 6
      storageName: s3-us-west
    - keep: 5
      name: daily-backup
      schedule: 0 0 * * *
      storageName: fs-pvc
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6G
      s3-us-west:
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
        type: s3
        verifyTLS: true
  crVersion: 1.11.0
  enableCRValidationWebhook: true
  haproxy:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-haproxy
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    podSecurityContext: {}
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 100M
  pmm:
    enabled: false
    image: percona/pmm-client:2.28.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 300m
        memory: 150M
    serverHost: monitoring-service
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: false
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    sidecars:
    - args: null
      command:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      env: []
      envFrom:
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef:
          name: ACTOKEY
          optional: null
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: null
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders: null
            path: ACTOKEY
            port: 1
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
        preStop:
          exec:
            command: []
          httpGet:
            host: ACTOKEY
            httpHeaders: []
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: 1
      livenessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 0
        grpc: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 3
        periodSeconds: 4
        successThreshold: 2
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        terminationGracePeriodSeconds: 2
        timeoutSeconds: 0
      name: ACTOKEY
      ports:
      - containerPort: 2
        hostIP: null
        hostPort: 0
        name: null
        protocol: ACTOKEY
      - containerPort: 3
        hostIP: null
        hostPort: null
        name: ACTOKEY
        protocol: ACTOKEY
      readinessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 2
        grpc: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 3
        periodSeconds: 0
        successThreshold: 5
        tcpSocket:
          host: ACTOKEY
          port: 5
        terminationGracePeriodSeconds: 4
        timeoutSeconds: 2
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add: null
          drop: []
        privileged: false
        procMount: ACTOKEY
        readOnlyRootFilesystem: true
        runAsGroup: 4
        runAsNonRoot: false
        runAsUser: 5
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile:
          localhostProfile: ACTOKEY
          type: ACTOKEY
        windowsOptions:
          gmsaCredentialSpec: ACTOKEY
          gmsaCredentialSpecName: null
          hostProcess: true
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 4
        grpc:
          port: 4
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 2
          scheme: ACTOKEY
        initialDelaySeconds: 5
        periodSeconds: 1
        successThreshold: 5
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        terminationGracePeriodSeconds: 0
        timeoutSeconds: null
      stdin: true
      stdinOnce: true
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: ACTOKEY
      tty: true
      volumeDevices:
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      volumeMounts:
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: true
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      workingDir: ACTOKEY
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    autoRecovery: true
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    imagePullPolicy: IfNotPresent
    livenessDelaySec: 300
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 8.0-recommended
    schedule: 0 4 * * *
    versionServiceEndpoint: https://check.percona.com
