apiVersion: pxc.percona.com/v1-11-0
kind: PerconaXtraDBCluster
metadata:
  finalizers:
  - delete-pxc-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.11.0-pxc8.0-backup
    imagePullPolicy: IfNotPresent
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    schedule:
    - keep: 3
      name: sat-night-backup
      schedule: 0 0 * * 6
      storageName: s3-us-west
    - keep: 5
      name: daily-backup
      schedule: 0 0 * * *
      storageName: fs-pvc
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6G
      s3-us-west:
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
        type: s3
        verifyTLS: true
  crVersion: 1.11.0
  enableCRValidationWebhook: true
  haproxy:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-haproxy
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 100M
  pmm:
    enabled: false
    image: percona/pmm-client:2.28.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 300m
        memory: 150M
    serverHost: monitoring-service
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: false
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    autoRecovery: true
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    imagePullPolicy: IfNotPresent
    livenessDelaySec: 300
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    sidecars:
    - args:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      command:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      env:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: null
            divisor: 2
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: null
            optional: false
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom: null
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: null
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 1
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      - name: ACTOKEY
        value: null
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef: null
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
      envFrom:
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: 1
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
        preStop:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: null
            port: ACTOKEY
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: 5
      livenessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 3
        grpc: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 1
        periodSeconds: 1
        successThreshold: 2
        tcpSocket: null
        terminationGracePeriodSeconds: 0
        timeoutSeconds: 0
      name: ACTOKEY
      ports:
      - containerPort: 1
        hostIP: ACTOKEY
        hostPort: 2
        name: ACTOKEY
        protocol: ACTOKEY
      - containerPort: 4
        hostIP: ACTOKEY
        hostPort: 5
        name: ACTOKEY
        protocol: ACTOKEY
      - containerPort: 3
        hostIP: ACTOKEY
        hostPort: 4
        name: ACTOKEY
        protocol: ACTOKEY
      readinessProbe:
        exec:
          command:
          - ACTOKEY
        failureThreshold: 1
        grpc:
          port: 0
          service: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 5
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        terminationGracePeriodSeconds: 0
        timeoutSeconds: 3
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          drop:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        privileged: true
        procMount: ACTOKEY
        readOnlyRootFilesystem: null
        runAsGroup: 3
        runAsNonRoot: true
        runAsUser: 5
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile:
          localhostProfile: ACTOKEY
          type: ACTOKEY
        windowsOptions:
          gmsaCredentialSpec: ACTOKEY
          gmsaCredentialSpecName: ACTOKEY
          hostProcess: false
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 4
        grpc:
          port: 0
          service: ACTOKEY
        httpGet:
          host: null
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 4
        periodSeconds: 5
        successThreshold: 4
        tcpSocket:
          host: ACTOKEY
          port: 0
        terminationGracePeriodSeconds: 4
        timeoutSeconds: 4
      stdin: false
      stdinOnce: true
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: ACTOKEY
      tty: false
      volumeDevices: []
      volumeMounts:
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: true
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: null
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: null
      - mountPath: ACTOKEY
        mountPropagation: null
        name: ACTOKEY
        readOnly: true
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      workingDir: ACTOKEY
    - args:
      - ACTOKEY
      - ACTOKEY
      command:
      - ACTOKEY
      - ACTOKEY
      env:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: null
            divisor: '.069'
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      envFrom:
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: true
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef: null
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: true
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec:
            command:
            - ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: 0
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: 2
        preStop:
          exec:
            command: []
          httpGet:
            host: null
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: 5
            scheme: ACTOKEY
          tcpSocket: null
      livenessProbe: null
      name: ACTOKEY
      ports:
      - containerPort: 5
        hostIP: null
        hostPort: 4
        name: ACTOKEY
        protocol: ACTOKEY
      readinessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 2
        grpc:
          port: 2
          service: ACTOKEY
        httpGet: null
        initialDelaySeconds: 3
        periodSeconds: null
        successThreshold: 2
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        terminationGracePeriodSeconds: 1
        timeoutSeconds: 3
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - ACTOKEY
          drop:
          - ACTOKEY
        privileged: null
        procMount: ACTOKEY
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 5
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile:
          localhostProfile: ACTOKEY
          type: ACTOKEY
        windowsOptions:
          gmsaCredentialSpec: ACTOKEY
          gmsaCredentialSpecName: ACTOKEY
          hostProcess: false
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 0
        grpc:
          port: 4
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders: null
          path: null
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: null
        periodSeconds: null
        successThreshold: 0
        tcpSocket:
          host: ACTOKEY
          port: 2
        terminationGracePeriodSeconds: null
        timeoutSeconds: null
      stdin: null
      stdinOnce: true
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: null
      tty: false
      volumeDevices: null
      volumeMounts:
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: true
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      workingDir: ACTOKEY
    - args:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      command: null
      env: null
      envFrom:
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef:
          name: ACTOKEY
          optional: null
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: null
          optional: false
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: true
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec:
            command: []
          httpGet:
            host: ACTOKEY
            httpHeaders: null
            path: ACTOKEY
            port: 4
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
        preStop:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: 1
            scheme: ACTOKEY
          tcpSocket: null
      livenessProbe:
        exec: null
        failureThreshold: 0
        grpc:
          port: 5
          service: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 2
          scheme: ACTOKEY
        initialDelaySeconds: 1
        periodSeconds: 3
        successThreshold: 1
        tcpSocket:
          host: null
          port: 2
        terminationGracePeriodSeconds: 5
        timeoutSeconds: 1
      name: ACTOKEY
      ports: []
      readinessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
        failureThreshold: null
        grpc:
          port: 1
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: null
          port: 2
          scheme: ACTOKEY
        initialDelaySeconds: 1
        periodSeconds: 5
        successThreshold: null
        tcpSocket:
          host: null
          port: 3
        terminationGracePeriodSeconds: 2
        timeoutSeconds: 2
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - ACTOKEY
          drop:
          - ACTOKEY
        privileged: null
        procMount: ACTOKEY
        readOnlyRootFilesystem: false
        runAsGroup: 4
        runAsNonRoot: true
        runAsUser: null
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile:
          localhostProfile: ACTOKEY
          type: ACTOKEY
        windowsOptions:
          gmsaCredentialSpec: ACTOKEY
          gmsaCredentialSpecName: ACTOKEY
          hostProcess: true
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command: []
        failureThreshold: 5
        grpc:
          port: 2
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 1
          scheme: ACTOKEY
        initialDelaySeconds: 0
        periodSeconds: null
        successThreshold: 5
        tcpSocket: null
        terminationGracePeriodSeconds: 5
        timeoutSeconds: 2
      stdin: false
      stdinOnce: false
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: ACTOKEY
      tty: true
      volumeDevices: []
      volumeMounts:
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: null
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      workingDir: ACTOKEY
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 8.0-recommended
    schedule: 0 4 * * *
    versionServiceEndpoint: https://check.percona.com
