apiVersion: pxc.percona.com/v1-11-0
kind: PerconaXtraDBCluster
metadata:
  finalizers:
  - delete-pxc-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.11.0-pxc8.0-backup
    imagePullPolicy: IfNotPresent
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    schedule:
    - keep: 3
      name: sat-night-backup
      schedule: 0 0 * * 6
      storageName: s3-us-west
    - keep: 5
      name: daily-backup
      schedule: 0 0 * * *
      storageName: fs-pvc
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6G
      s3-us-west:
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
        type: s3
        verifyTLS: true
  crVersion: 1.11.0
  enableCRValidationWebhook: true
  haproxy:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-haproxy
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 100M
  pmm:
    enabled: false
    image: percona/pmm-client:2.28.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 300m
        memory: 150M
    serverHost: monitoring-service
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    annotations:
      ACTOKEY: ''
    enabled: false
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    sidecarVolumes:
    - awsElasticBlockStore:
        fsType: ACTOKEY
        partition: 3
        readOnly: true
        volumeID: ACTOKEY
      azureDisk:
        cachingMode: ACTOKEY
        diskName: ACTOKEY
        diskURI: ACTOKEY
        fsType: ACTOKEY
        kind: ACTOKEY
        readOnly: null
      azureFile:
        readOnly: false
        secretName: ACTOKEY
        shareName: ACTOKEY
      cephfs:
        monitors: []
        path: ACTOKEY
        readOnly: true
        secretFile: ACTOKEY
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      cinder:
        fsType: ACTOKEY
        readOnly: null
        secretRef:
          name: ACTOKEY
        volumeID: ACTOKEY
      configMap:
        defaultMode: 0
        items:
        - key: ACTOKEY
          mode: 1
          path: ACTOKEY
        name: ACTOKEY
        optional: false
      csi:
        driver: ACTOKEY
        fsType: ACTOKEY
        nodePublishSecretRef:
          name: ACTOKEY
        readOnly: false
        volumeAttributes:
          ACTOKEY: ACTOKEY
      downwardAPI: null
      emptyDir: null
      ephemeral:
        volumeClaimTemplate:
          metadata: null
          spec:
            accessModes:
            - ACTOKEY
            dataSource:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            dataSourceRef:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            resources:
              limits:
                ACTOKEY: 1
              requests:
                ACTOKEY: 3
            selector:
              matchExpressions:
              - key: ACTOKEY
                operator: ACTOKEY
                values:
                - ACTOKEY
                - ACTOKEY
              matchLabels:
                ACTOKEY: ACTOKEY
            storageClassName: ACTOKEY
            volumeMode: ACTOKEY
            volumeName: ACTOKEY
      fc:
        fsType: ACTOKEY
        lun: 4
        readOnly: false
        targetWWNs: []
        wwids:
        - ACTOKEY
        - ACTOKEY
      flexVolume:
        driver: ACTOKEY
        fsType: ACTOKEY
        options:
          ACTOKEY: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
      flocker:
        datasetName: ACTOKEY
        datasetUUID: ACTOKEY
      gcePersistentDisk:
        fsType: ACTOKEY
        partition: null
        pdName: ACTOKEY
        readOnly: true
      gitRepo:
        directory: ACTOKEY
        repository: ACTOKEY
        revision: ACTOKEY
      glusterfs:
        endpoints: ACTOKEY
        path: ACTOKEY
        readOnly: false
      hostPath:
        path: ACTOKEY
        type: ACTOKEY
      iscsi:
        chapAuthDiscovery: true
        chapAuthSession: null
        fsType: null
        initiatorName: ACTOKEY
        iqn: ACTOKEY
        iscsiInterface: ACTOKEY
        lun: 3
        portals:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        targetPortal: ACTOKEY
      name: ACTOKEY
      nfs:
        path: ACTOKEY
        readOnly: false
        server: ACTOKEY
      persistentVolumeClaim:
        claimName: ACTOKEY
        readOnly: true
      photonPersistentDisk:
        fsType: null
        pdID: ACTOKEY
      portworxVolume: null
      projected:
        defaultMode: 2
        sources: null
      quobyte:
        group: ACTOKEY
        readOnly: false
        registry: ACTOKEY
        tenant: ACTOKEY
        user: null
        volume: ACTOKEY
      rbd:
        fsType: ACTOKEY
        image: ACTOKEY
        keyring: ACTOKEY
        monitors:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        pool: ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      scaleIO:
        fsType: ACTOKEY
        gateway: ACTOKEY
        protectionDomain: ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        sslEnabled: true
        storageMode: ACTOKEY
        storagePool: ACTOKEY
        system: ACTOKEY
        volumeName: ACTOKEY
      secret:
        defaultMode: 5
        items:
        - key: ACTOKEY
          mode: 2
          path: ACTOKEY
        - key: ACTOKEY
          mode: 1
          path: ACTOKEY
        - key: ACTOKEY
          mode: 3
          path: ACTOKEY
        - key: ACTOKEY
          mode: null
          path: ACTOKEY
        optional: false
        secretName: ACTOKEY
      storageos:
        fsType: null
        readOnly: true
        secretRef:
          name: ACTOKEY
        volumeName: ACTOKEY
        volumeNamespace: ACTOKEY
      vsphereVolume:
        fsType: ACTOKEY
        storagePolicyID: ACTOKEY
        storagePolicyName: null
        volumePath: ACTOKEY
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    autoRecovery: true
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    imagePullPolicy: IfNotPresent
    livenessDelaySec: 300
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 8.0-recommended
    schedule: 0 4 * * *
    versionServiceEndpoint: https://check.percona.com
