apiVersion: pxc.percona.com/v1-11-0
kind: PerconaXtraDBCluster
metadata:
  finalizers:
  - delete-pxc-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.11.0-pxc8.0-backup
    imagePullPolicy: IfNotPresent
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    schedule:
    - keep: 3
      name: sat-night-backup
      schedule: 0 0 * * 6
      storageName: s3-us-west
    - keep: 5
      name: daily-backup
      schedule: 0 0 * * *
      storageName: fs-pvc
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6G
      s3-us-west:
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
        type: s3
        verifyTLS: true
  crVersion: 1.11.0
  enableCRValidationWebhook: true
  haproxy:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-haproxy
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 100M
  pmm:
    enabled: false
    image: percona/pmm-client:2.28.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 300m
        memory: 150M
    serverHost: monitoring-service
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: false
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    sidecarPVCs:
    - apiVersion: ACTOKEY
      kind: ACTOKEY
      metadata: null
      spec:
        accessModes:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        dataSource:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        dataSourceRef:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        resources:
          limits:
            cpu: 800m
          requests:
            cpu: 800m
        selector:
          matchExpressions:
          - key: ACTOKEY
            operator: ACTOKEY
            values: []
          matchLabels:
            ACTOKEY: ACTOKEY
        storageClassName: ACTOKEY
        volumeMode: ACTOKEY
        volumeName: ACTOKEY
      status:
        accessModes:
        - ACTOKEY
        - ACTOKEY
        allocatedResources:
          ACTOKEY: '377'
        capacity:
          ACTOKEY: 5
        conditions:
        - lastProbeTime: ACTOKEY
          lastTransitionTime: ACTOKEY
          message: ACTOKEY
          reason: ACTOKEY
          status: ACTOKEY
          type: ACTOKEY
        - lastProbeTime: ACTOKEY
          lastTransitionTime: ACTOKEY
          message: null
          reason: null
          status: ACTOKEY
          type: ACTOKEY
        - lastProbeTime: ACTOKEY
          lastTransitionTime: ACTOKEY
          message: ACTOKEY
          reason: ACTOKEY
          status: ACTOKEY
          type: ACTOKEY
        - lastProbeTime: ACTOKEY
          lastTransitionTime: null
          message: ACTOKEY
          reason: ACTOKEY
          status: ACTOKEY
          type: ACTOKEY
        - lastProbeTime: ACTOKEY
          lastTransitionTime: null
          message: ACTOKEY
          reason: null
          status: ACTOKEY
          type: ACTOKEY
        phase: ACTOKEY
        resizeStatus: ACTOKEY
    - apiVersion: ACTOKEY
      kind: ACTOKEY
      metadata: null
      spec:
        accessModes:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        dataSource:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        dataSourceRef:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        resources:
          limits:
            cpu: 800m
          requests:
            cpu: 800m
        selector:
          matchExpressions:
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values: []
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values: []
          matchLabels:
            ACTOKEY: ACTOKEY
        storageClassName: ACTOKEY
        volumeMode: ACTOKEY
        volumeName: ACTOKEY
      status:
        accessModes: []
        allocatedResources:
          ACTOKEY: 1
        capacity:
          ACTOKEY: 2
        conditions: []
        phase: ACTOKEY
        resizeStatus: ACTOKEY
    - apiVersion: ACTOKEY
      kind: ACTOKEY
      metadata: null
      spec:
        accessModes:
        - ACTOKEY
        - ACTOKEY
        dataSource:
          apiGroup: ACTOKEY
          kind: ACTOKEY
          name: ACTOKEY
        dataSourceRef: null
        resources: null
        selector:
          matchExpressions:
          - key: ACTOKEY
            operator: ACTOKEY
            values: null
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values:
            - ACTOKEY
          - key: ACTOKEY
            operator: ACTOKEY
            values: []
          matchLabels:
            ACTOKEY: ACTOKEY
        storageClassName: ACTOKEY
        volumeMode: ACTOKEY
        volumeName: ACTOKEY
      status:
        accessModes:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        allocatedResources:
          ACTOKEY: .217442e.709892
        capacity:
          ACTOKEY: '.195885'
        conditions:
        - lastProbeTime: ACTOKEY
          lastTransitionTime: ACTOKEY
          message: ACTOKEY
          reason: null
          status: ACTOKEY
          type: ACTOKEY
        - lastProbeTime: ACTOKEY
          lastTransitionTime: ACTOKEY
          message: ACTOKEY
          reason: null
          status: ACTOKEY
          type: ACTOKEY
        - lastProbeTime: ACTOKEY
          lastTransitionTime: ACTOKEY
          message: ACTOKEY
          reason: ACTOKEY
          status: ACTOKEY
          type: ACTOKEY
        - lastProbeTime: ACTOKEY
          lastTransitionTime: ACTOKEY
          message: null
          reason: ACTOKEY
          status: ACTOKEY
          type: ACTOKEY
        phase: ACTOKEY
        resizeStatus: ACTOKEY
    - apiVersion: ACTOKEY
      kind: ACTOKEY
      metadata: null
      spec: null
      status:
        accessModes:
        - ACTOKEY
        allocatedResources:
          ACTOKEY: 4
        capacity:
          ACTOKEY: '+0626.68332'
        conditions: null
        phase: ACTOKEY
        resizeStatus: ACTOKEY
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    autoRecovery: true
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    imagePullPolicy: IfNotPresent
    livenessDelaySec: 300
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 8.0-recommended
    schedule: 0 4 * * *
    versionServiceEndpoint: https://check.percona.com
