apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: Always
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  pod:
    resources:
      limits:
        ACTOKEY: 1000m
        dbmxcmopve: 1000m
      requests:
        cpu: 800m
  replicas: 3
  storageType: persistence
