apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  containers:
  - args: []
    command: []
    env: null
    envFrom: null
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 2
          scheme: ACTOKEY
        tcpSocket: null
      preStop:
        exec: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: 4
    livenessProbe: null
    name: ACTOKEY
    ports:
    - containerPort: 0
      hostIP: ACTOKEY
      hostPort: 1
      name: ACTOKEY
      protocol: ACTOKEY
    - containerPort: 3
      hostIP: ACTOKEY
      hostPort: null
      name: ACTOKEY
      protocol: ACTOKEY
    readinessProbe:
      exec: null
      failureThreshold: 4
      httpGet:
        host: ACTOKEY
        httpHeaders: null
        path: ACTOKEY
        port: 5
        scheme: ACTOKEY
      initialDelaySeconds: 4
      periodSeconds: 2
      successThreshold: 4
      tcpSocket:
        host: ACTOKEY
        port: 1
      timeoutSeconds: 5
    resources: null
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - ACTOKEY
        - ACTOKEY
        drop:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      privileged: true
      procMount: ACTOKEY
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 2
      seLinuxOptions: null
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: ACTOKEY
        gmsaCredentialSpecName: ACTOKEY
        runAsUserName: ACTOKEY
    startupProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 1
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 4
        scheme: ACTOKEY
      initialDelaySeconds: 4
      periodSeconds: 1
      successThreshold: 1
      tcpSocket:
        host: ACTOKEY
        port: 3
      timeoutSeconds: 5
    stdin: false
    stdinOnce: null
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: false
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts: []
    workingDir: ACTOKEY
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  probes:
    readinessProbe:
      failureThreshold: 0
  replicas: 3
  storageType: persistence
