apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: test-cluster
spec:
  configUpdateStrategy: RollingUpdate
  enableDynamicConfiguration: true
  helper:
    image: busybox:1.34.1
  pd:
    baseImage: pingcap/pd
    config: "[dashboard]\n  internal-proxy = true\n"
    maxFailoverCount: 0
    mountClusterClientSecret: true
    replicas: 3
    requests:
      storage: 10Gi
  pvReclaimPolicy: Retain
  tidb:
    additionalVolumes:
    - awsElasticBlockStore:
        fsType: ACTOKEY
        partition: 1
        readOnly: false
        volumeID: ACTOKEY
      azureDisk:
        cachingMode: ACTOKEY
        diskName: ACTOKEY
        diskURI: ACTOKEY
        fsType: ACTOKEY
        kind: ACTOKEY
        readOnly: false
      azureFile: null
      cephfs:
        monitors:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        path: ACTOKEY
        readOnly: true
        secretFile: ACTOKEY
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      cinder:
        fsType: null
        readOnly: false
        secretRef:
          name: ACTOKEY
        volumeID: ACTOKEY
      configMap:
        defaultMode: 5
        items:
        - key: ACTOKEY
          mode: 1
          path: ACTOKEY
        - key: ACTOKEY
          mode: 2
          path: ACTOKEY
        name: null
        optional: true
      csi:
        driver: ACTOKEY
        fsType: ACTOKEY
        nodePublishSecretRef:
          name: null
        readOnly: false
        volumeAttributes:
          ACTOKEY: ACTOKEY
      downwardAPI:
        defaultMode: 2
        items:
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 4
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 3
            resource: ACTOKEY
        - fieldRef: null
          mode: 3
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 3
            resource: ACTOKEY
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 1
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 4
            resource: ACTOKEY
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 0
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: .43064979G
            resource: ACTOKEY
      emptyDir:
        medium: ACTOKEY
        sizeLimit: 17241E3409505.3
      ephemeral: null
      fc:
        fsType: ACTOKEY
        lun: 2
        readOnly: true
        targetWWNs:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        wwids:
        - ACTOKEY
      flexVolume:
        driver: ACTOKEY
        fsType: ACTOKEY
        options:
          ACTOKEY: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
      flocker: null
      gcePersistentDisk:
        fsType: ACTOKEY
        partition: 3
        pdName: ACTOKEY
        readOnly: true
      gitRepo:
        directory: null
        repository: ACTOKEY
        revision: ACTOKEY
      glusterfs:
        endpoints: ACTOKEY
        path: ACTOKEY
        readOnly: true
      hostPath:
        path: ACTOKEY
        type: ACTOKEY
      iscsi:
        chapAuthDiscovery: true
        chapAuthSession: true
        fsType: ACTOKEY
        initiatorName: ACTOKEY
        iqn: ACTOKEY
        iscsiInterface: ACTOKEY
        lun: 0
        portals:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        targetPortal: ACTOKEY
      name: ACTOKEY
      nfs:
        path: ACTOKEY
        readOnly: true
        server: ACTOKEY
      persistentVolumeClaim:
        claimName: ACTOKEY
        readOnly: true
      photonPersistentDisk:
        fsType: ACTOKEY
        pdID: ACTOKEY
      portworxVolume:
        fsType: ACTOKEY
        readOnly: false
        volumeID: ACTOKEY
      projected:
        defaultMode: null
        sources: []
      quobyte:
        group: ACTOKEY
        readOnly: false
        registry: ACTOKEY
        tenant: ACTOKEY
        user: ACTOKEY
        volume: ACTOKEY
      rbd:
        fsType: ACTOKEY
        image: ACTOKEY
        keyring: ACTOKEY
        monitors:
        - ACTOKEY
        pool: ACTOKEY
        readOnly: true
        secretRef:
          name: null
        user: ACTOKEY
      scaleIO:
        fsType: ACTOKEY
        gateway: ACTOKEY
        protectionDomain: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        sslEnabled: null
        storageMode: ACTOKEY
        storagePool: ACTOKEY
        system: ACTOKEY
        volumeName: ACTOKEY
      secret:
        defaultMode: 1
        items:
        - key: ACTOKEY
          mode: 5
          path: ACTOKEY
        - key: ACTOKEY
          mode: 4
          path: ACTOKEY
        - key: ACTOKEY
          mode: 5
          path: ACTOKEY
        - key: ACTOKEY
          mode: 5
          path: ACTOKEY
        - key: ACTOKEY
          mode: 4
          path: ACTOKEY
        optional: false
        secretName: ACTOKEY
      storageos:
        fsType: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        volumeName: ACTOKEY
        volumeNamespace: ACTOKEY
      vsphereVolume:
        fsType: ACTOKEY
        storagePolicyID: ACTOKEY
        storagePolicyName: ACTOKEY
        volumePath: ACTOKEY
    baseImage: pingcap/tidb
    config: "[performance]\n  tcp-keep-alive = true\n"
    maxFailoverCount: 0
    replicas: 3
    service:
      externalTrafficPolicy: Local
      type: NodePort
  tikv:
    baseImage: pingcap/tikv
    config: 'log-level = "info"

      '
    maxFailoverCount: 0
    mountClusterClientSecret: true
    recoverFailover: false
    replicas: 3
    requests:
      storage: 100Gi
    separateRaftLog: true
  timezone: UTC
  version: v5.4.0
