apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq-system
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: null
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-cluster
        topologyKey: kubernetes.io/hostname
  image: null
  imagePullSecrets: null
  override:
    statefulSet:
      spec:
        volumeClaimTemplates:
        - apiVersion: null
          kind: ACTOKEY
          metadata:
            annotations:
              ACTOKEY: ACTOKEY
            labels: null
            name: ACTOKEY
            namespace: ACTOKEY
          spec:
            accessModes:
            - ACTOKEY
            - ACTOKEY
            dataSource:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            resources:
              limits:
                ACTOKEY: '.0521'
              requests:
                ACTOKEY: 1
            selector:
              matchExpressions:
              - key: ACTOKEY
                operator: ACTOKEY
                values: []
              - key: ACTOKEY
                operator: ACTOKEY
                values: []
              matchLabels:
                ACTOKEY: ACTOKEY
            storageClassName: ACTOKEY
            volumeMode: ACTOKEY
            volumeName: ACTOKEY
  persistence:
    storage: 50Gi
  rabbitmq:
    additionalConfig: 'cluster_partition_handling = pause_minority

      vm_memory_high_watermark_paging_ratio = 0.99

      disk_free_limit.relative = 1.0

      collect_statistics_interval = 10000

      '
  replicas: 3
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  secretBackend:
    vault:
      tls:
        pkiIssuerPath: ''
  service:
    type: ClusterIP
  skipPostDeploySteps: false
  terminationGracePeriodSeconds: 1024
  tls:
    caSecretName: null
    disableNonTLSListeners: false
    secretName: null
  tolerations: null
