apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: test-cluster
  namespace: knative-eventing
spec:
  additionalManifests:
  - URL: ''
  config:
    config-kreference-mapping:
      key1: value1
  deployments:
  - affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
              - kind-worker2
              - kind-worker3kind-control-plane
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - test-cluster
          topologyKey: kubernetes.io/hostname
    env:
    - container: eventing-controller
      envVars:
      - name: ENVAR_1
        value: VALUE_1
    name: eventing-controller
    resources:
    - container: eventing-controller
      limits:
        cpu: 1000m
        memory: 250M
      requests:
        cpu: 300m
        memory: 100M
  podDisruptionBudgets:
  - minAvailable: 50%
    name: eventing-webhook
  services:
  - name: eventing-webhook
  version: 1.6.0
