apiVersion: pxc.percona.com/v1-11-0
kind: PerconaXtraDBCluster
metadata:
  finalizers:
  - delete-pxc-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.11.0-pxc8.0-backup
    imagePullPolicy: IfNotPresent
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    schedule:
    - keep: 3
      name: sat-night-backup
      schedule: 0 0 * * 6
      storageName: s3-us-west
    - keep: 5
      name: daily-backup
      schedule: 0 0 * * *
      storageName: fs-pvc
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6G
      s3-us-west:
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
        type: s3
        verifyTLS: true
  crVersion: 1.11.0
  enableCRValidationWebhook: true
  haproxy:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-haproxy
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 100M
  pmm:
    enabled: false
    image: percona/pmm-client:2.28.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 300m
        memory: 150M
    serverHost: monitoring-service
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: false
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    autoRecovery: true
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    imagePullPolicy: IfNotPresent
    livenessDelaySec: 300
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    sidecarVolumes:
    - awsElasticBlockStore:
        fsType: ACTOKEY
        partition: null
        readOnly: false
        volumeID: ACTOKEY
      azureDisk:
        cachingMode: ACTOKEY
        diskName: ACTOKEY
        diskURI: ACTOKEY
        fsType: null
        kind: ACTOKEY
        readOnly: false
      azureFile:
        readOnly: true
        secretName: ACTOKEY
        shareName: ACTOKEY
      cephfs:
        monitors:
        - ACTOKEY
        - ACTOKEY
        path: ACTOKEY
        readOnly: false
        secretFile: ACTOKEY
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      cinder:
        fsType: ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        volumeID: ACTOKEY
      configMap:
        defaultMode: 3
        items:
        - key: ACTOKEY
          mode: 0
          path: ACTOKEY
        - key: ACTOKEY
          mode: 1
          path: ACTOKEY
        - key: ACTOKEY
          mode: 5
          path: ACTOKEY
        name: ACTOKEY
        optional: true
      csi: null
      downwardAPI:
        defaultMode: 2
        items: []
      emptyDir:
        medium: ACTOKEY
        sizeLimit: '+87339718.e+51676'
      ephemeral:
        volumeClaimTemplate:
          metadata: null
          spec:
            accessModes:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            dataSource:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            dataSourceRef:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            resources:
              limits:
                ACTOKEY: .323044503M
              requests:
                ACTOKEY: 3
            selector:
              matchExpressions:
              - key: ACTOKEY
                operator: ACTOKEY
                values: null
              - key: ACTOKEY
                operator: ACTOKEY
                values: null
              - key: ACTOKEY
                operator: ACTOKEY
                values:
                - ACTOKEY
                - ACTOKEY
              matchLabels:
                ACTOKEY: ACTOKEY
            storageClassName: ACTOKEY
            volumeMode: ACTOKEY
            volumeName: ACTOKEY
      fc:
        fsType: ACTOKEY
        lun: 0
        readOnly: true
        targetWWNs: null
        wwids: []
      flexVolume:
        driver: ACTOKEY
        fsType: ACTOKEY
        options:
          ACTOKEY: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
      flocker:
        datasetName: ACTOKEY
        datasetUUID: null
      gcePersistentDisk:
        fsType: ACTOKEY
        partition: 5
        pdName: ACTOKEY
        readOnly: true
      gitRepo:
        directory: null
        repository: ACTOKEY
        revision: ACTOKEY
      glusterfs:
        endpoints: ACTOKEY
        path: ACTOKEY
        readOnly: true
      hostPath: null
      iscsi:
        chapAuthDiscovery: false
        chapAuthSession: true
        fsType: ACTOKEY
        initiatorName: ACTOKEY
        iqn: ACTOKEY
        iscsiInterface: ACTOKEY
        lun: 5
        portals:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        targetPortal: ACTOKEY
      name: ACTOKEY
      nfs:
        path: ACTOKEY
        readOnly: false
        server: ACTOKEY
      persistentVolumeClaim:
        claimName: ACTOKEY
        readOnly: true
      photonPersistentDisk:
        fsType: null
        pdID: ACTOKEY
      portworxVolume:
        fsType: ACTOKEY
        readOnly: false
        volumeID: ACTOKEY
      projected:
        defaultMode: 3
        sources:
        - configMap: null
          downwardAPI:
            items:
            - fieldRef:
                apiVersion: null
                fieldPath: ACTOKEY
              mode: 2
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: null
                resource: ACTOKEY
            - fieldRef:
                apiVersion: null
                fieldPath: ACTOKEY
              mode: 1
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: -312k
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 0
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: null
                resource: ACTOKEY
            - fieldRef: null
              mode: 4
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: 4
                resource: ACTOKEY
          secret:
            items:
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 5
            path: ACTOKEY
        - configMap:
            items:
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          downwardAPI: null
          secret:
            items:
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            name: ACTOKEY
            optional: null
          serviceAccountToken: null
        - configMap:
            items: []
            name: ACTOKEY
            optional: false
          downwardAPI:
            items:
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 0
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: null
                resource: ACTOKEY
            - fieldRef:
                apiVersion: null
                fieldPath: ACTOKEY
              mode: 0
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: +7512M
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 0
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: .291e2
                resource: ACTOKEY
          secret:
            items:
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            - key: ACTOKEY
              mode: 1
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 5
            path: ACTOKEY
      quobyte:
        group: ACTOKEY
        readOnly: true
        registry: ACTOKEY
        tenant: ACTOKEY
        user: ACTOKEY
        volume: ACTOKEY
      rbd:
        fsType: null
        image: ACTOKEY
        keyring: ACTOKEY
        monitors:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        pool: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      scaleIO:
        fsType: null
        gateway: ACTOKEY
        protectionDomain: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        sslEnabled: false
        storageMode: ACTOKEY
        storagePool: ACTOKEY
        system: ACTOKEY
        volumeName: ACTOKEY
      secret: null
      storageos: null
      vsphereVolume: null
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 8.0-recommended
    schedule: 0 4 * * *
    versionServiceEndpoint: https://check.percona.com
