apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  replicas: 3
  storageType: persistence
  volumes:
  - awsElasticBlockStore:
      fsType: ACTOKEY
      partition: 0
      readOnly: true
      volumeID: ACTOKEY
    azureDisk:
      cachingMode: ACTOKEY
      diskName: ACTOKEY
      diskURI: ACTOKEY
      fsType: ACTOKEY
      kind: ACTOKEY
      readOnly: false
    azureFile:
      readOnly: true
      secretName: ACTOKEY
      shareName: ACTOKEY
    cephfs:
      monitors: []
      path: ACTOKEY
      readOnly: false
      secretFile: ACTOKEY
      secretRef:
        name: ACTOKEY
      user: ACTOKEY
    cinder:
      fsType: ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
      volumeID: ACTOKEY
    configMap:
      defaultMode: 2
      items: []
      name: ACTOKEY
      optional: true
    csi:
      driver: ACTOKEY
      fsType: ACTOKEY
      nodePublishSecretRef:
        name: ACTOKEY
      readOnly: false
      volumeAttributes:
        ACTOKEY: ACTOKEY
    downwardAPI:
      defaultMode: 4
      items:
      - fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        mode: 4
        path: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: null
          resource: ACTOKEY
    emptyDir:
      medium: null
      sizeLimit: +46029.1941Mi
    ephemeral:
      readOnly: false
      volumeClaimTemplate:
        metadata: null
        spec:
          accessModes:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          dataSource:
            apiGroup: ACTOKEY
            kind: ACTOKEY
            name: ACTOKEY
          resources: null
          selector:
            matchExpressions: []
            matchLabels: null
          storageClassName: ACTOKEY
          volumeMode: ACTOKEY
          volumeName: null
    fc:
      fsType: ACTOKEY
      lun: 3
      readOnly: true
      targetWWNs: null
      wwids:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
    flexVolume:
      driver: ACTOKEY
      fsType: ACTOKEY
      options:
        ACTOKEY: ACTOKEY
      readOnly: true
      secretRef:
        name: null
    flocker:
      datasetName: ACTOKEY
      datasetUUID: ACTOKEY
    gcePersistentDisk:
      fsType: ACTOKEY
      partition: 4
      pdName: ACTOKEY
      readOnly: false
    gitRepo:
      directory: ACTOKEY
      repository: ACTOKEY
      revision: ACTOKEY
    glusterfs:
      endpoints: ACTOKEY
      path: ACTOKEY
      readOnly: true
    hostPath:
      path: ACTOKEY
      type: ACTOKEY
    iscsi:
      chapAuthDiscovery: true
      chapAuthSession: false
      fsType: ACTOKEY
      initiatorName: ACTOKEY
      iqn: ACTOKEY
      iscsiInterface: ACTOKEY
      lun: 4
      portals:
      - ACTOKEY
      - ACTOKEY
      readOnly: null
      secretRef:
        name: ACTOKEY
      targetPortal: ACTOKEY
    name: ACTOKEY
    nfs:
      path: ACTOKEY
      readOnly: true
      server: ACTOKEY
    persistentVolumeClaim:
      claimName: ACTOKEY
      readOnly: true
    photonPersistentDisk: null
    portworxVolume:
      fsType: ACTOKEY
      readOnly: true
      volumeID: ACTOKEY
    projected: null
    quobyte:
      group: ACTOKEY
      readOnly: true
      registry: ACTOKEY
      tenant: ACTOKEY
      user: ACTOKEY
      volume: ACTOKEY
    rbd:
      fsType: ACTOKEY
      image: ACTOKEY
      keyring: ACTOKEY
      monitors:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      pool: ACTOKEY
      readOnly: true
      secretRef:
        name: ACTOKEY
      user: ACTOKEY
    scaleIO:
      fsType: ACTOKEY
      gateway: ACTOKEY
      protectionDomain: ACTOKEY
      readOnly: null
      secretRef:
        name: ACTOKEY
      sslEnabled: true
      storageMode: ACTOKEY
      storagePool: ACTOKEY
      system: ACTOKEY
      volumeName: ACTOKEY
    secret:
      defaultMode: 4
      items:
      - key: ACTOKEY
        mode: 4
        path: ACTOKEY
      optional: false
      secretName: ACTOKEY
    storageos: null
    vsphereVolume:
      fsType: ACTOKEY
      storagePolicyID: ACTOKEY
      storagePolicyName: ACTOKEY
      volumePath: ACTOKEY
  - awsElasticBlockStore:
      fsType: ACTOKEY
      partition: null
      readOnly: true
      volumeID: ACTOKEY
    azureDisk:
      cachingMode: ACTOKEY
      diskName: ACTOKEY
      diskURI: ACTOKEY
      fsType: null
      kind: ACTOKEY
      readOnly: false
    azureFile:
      readOnly: false
      secretName: ACTOKEY
      shareName: ACTOKEY
    cephfs: null
    cinder:
      fsType: ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
      volumeID: ACTOKEY
    configMap:
      defaultMode: null
      items:
      - key: ACTOKEY
        mode: 3
        path: ACTOKEY
      - key: ACTOKEY
        mode: 5
        path: ACTOKEY
      - key: ACTOKEY
        mode: 3
        path: ACTOKEY
      - key: ACTOKEY
        mode: 2
        path: ACTOKEY
      name: ACTOKEY
      optional: false
    csi:
      driver: ACTOKEY
      fsType: ACTOKEY
      nodePublishSecretRef:
        name: ACTOKEY
      readOnly: false
      volumeAttributes:
        ACTOKEY: ACTOKEY
    downwardAPI:
      defaultMode: null
      items: []
    emptyDir:
      medium: ACTOKEY
      sizeLimit: '348676310.507694937'
    ephemeral:
      readOnly: false
      volumeClaimTemplate:
        metadata: null
        spec:
          accessModes:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          dataSource:
            apiGroup: ACTOKEY
            kind: ACTOKEY
            name: ACTOKEY
          resources:
            limits: null
            requests:
              ACTOKEY: '.8784836199'
          selector:
            matchExpressions: []
            matchLabels:
              ACTOKEY: ACTOKEY
          storageClassName: ACTOKEY
          volumeMode: ACTOKEY
          volumeName: ACTOKEY
    fc:
      fsType: ACTOKEY
      lun: 1
      readOnly: null
      targetWWNs:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      wwids:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
    flexVolume:
      driver: ACTOKEY
      fsType: ACTOKEY
      options:
        ACTOKEY: ACTOKEY
      readOnly: null
      secretRef:
        name: null
    flocker:
      datasetName: ACTOKEY
      datasetUUID: ACTOKEY
    gcePersistentDisk: null
    gitRepo:
      directory: ACTOKEY
      repository: ACTOKEY
      revision: null
    glusterfs:
      endpoints: ACTOKEY
      path: ACTOKEY
      readOnly: false
    hostPath:
      path: ACTOKEY
      type: ACTOKEY
    iscsi:
      chapAuthDiscovery: false
      chapAuthSession: true
      fsType: ACTOKEY
      initiatorName: ACTOKEY
      iqn: ACTOKEY
      iscsiInterface: ACTOKEY
      lun: 1
      portals:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
      targetPortal: ACTOKEY
    name: ACTOKEY
    nfs:
      path: ACTOKEY
      readOnly: true
      server: ACTOKEY
    persistentVolumeClaim:
      claimName: ACTOKEY
      readOnly: false
    photonPersistentDisk:
      fsType: ACTOKEY
      pdID: ACTOKEY
    portworxVolume:
      fsType: ACTOKEY
      readOnly: false
      volumeID: ACTOKEY
    projected:
      defaultMode: 1
      sources:
      - configMap:
          items:
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        downwardAPI:
          items:
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 0
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: .6Ki
              resource: ACTOKEY
        secret:
          items:
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        serviceAccountToken:
          audience: null
          expirationSeconds: 5
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        downwardAPI:
          items:
          - fieldRef: null
            mode: 4
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: '+47344202'
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 0
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: null
              resource: ACTOKEY
        secret:
          items:
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 4
          path: ACTOKEY
      - configMap:
          items: null
          name: ACTOKEY
          optional: true
        downwardAPI:
          items: []
        secret:
          items:
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 3
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        downwardAPI:
          items:
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 5
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 1
              resource: ACTOKEY
          - fieldRef:
              apiVersion: null
              fieldPath: ACTOKEY
            mode: null
            path: ACTOKEY
            resourceFieldRef:
              containerName: null
              divisor: null
              resource: ACTOKEY
        secret:
          items:
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          name: null
          optional: true
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 0
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        downwardAPI:
          items:
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: null
            path: ACTOKEY
            resourceFieldRef: null
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 5
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 452.17628e-598.412353038
              resource: ACTOKEY
        secret:
          items: []
          name: null
          optional: true
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 5
          path: ACTOKEY
    quobyte:
      group: ACTOKEY
      readOnly: true
      registry: ACTOKEY
      tenant: ACTOKEY
      user: null
      volume: ACTOKEY
    rbd:
      fsType: null
      image: ACTOKEY
      keyring: ACTOKEY
      monitors:
      - ACTOKEY
      pool: ACTOKEY
      readOnly: true
      secretRef:
        name: ACTOKEY
      user: ACTOKEY
    scaleIO:
      fsType: ACTOKEY
      gateway: ACTOKEY
      protectionDomain: ACTOKEY
      readOnly: true
      secretRef:
        name: ACTOKEY
      sslEnabled: true
      storageMode: ACTOKEY
      storagePool: ACTOKEY
      system: ACTOKEY
      volumeName: ACTOKEY
    secret:
      defaultMode: 4
      items:
      - key: ACTOKEY
        mode: 5
        path: ACTOKEY
      - key: ACTOKEY
        mode: 2
        path: ACTOKEY
      - key: ACTOKEY
        mode: 0
        path: ACTOKEY
      - key: ACTOKEY
        mode: 0
        path: ACTOKEY
      optional: true
      secretName: null
    storageos:
      fsType: ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
      volumeName: ACTOKEY
      volumeNamespace: ACTOKEY
    vsphereVolume:
      fsType: ACTOKEY
      storagePolicyID: ACTOKEY
      storagePolicyName: ACTOKEY
      volumePath: ACTOKEY
