apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  containers:
  - args: null
    command:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: null
          optional: false
        fieldRef: null
        resourceFieldRef: null
        secretKeyRef:
          key: ACTOKEY
          name: null
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: null
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 4
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '-195585'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: +.143214580e.19363400
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    envFrom:
    - configMapRef: null
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    - configMapRef:
        name: ACTOKEY
        optional: null
      prefix: ACTOKEY
      secretRef:
        name: null
        optional: null
    - configMapRef:
        name: ACTOKEY
        optional: false
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: true
    - configMapRef:
        name: ACTOKEY
        optional: null
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: true
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders: []
          path: ACTOKEY
          port: 1
          scheme: null
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
      preStop:
        exec:
          command:
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: null
          port: ACTOKEY
    livenessProbe:
      exec: null
      failureThreshold: 5
      httpGet: null
      initialDelaySeconds: 4
      periodSeconds: 3
      successThreshold: 4
      tcpSocket:
        host: ACTOKEY
        port: 5
      timeoutSeconds: null
    name: ACTOKEY
    ports:
    - containerPort: 1
      hostIP: ACTOKEY
      hostPort: 2
      name: null
      protocol: ACTOKEY
    - containerPort: 0
      hostIP: ACTOKEY
      hostPort: 3
      name: ACTOKEY
      protocol: ACTOKEY
    - containerPort: 1
      hostIP: ACTOKEY
      hostPort: 3
      name: null
      protocol: ACTOKEY
    - containerPort: 3
      hostIP: ACTOKEY
      hostPort: 4
      name: ACTOKEY
      protocol: ACTOKEY
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 5
      httpGet:
        host: ACTOKEY
        httpHeaders: []
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 4
      periodSeconds: 4
      successThreshold: 1
      tcpSocket:
        host: ACTOKEY
        port: 3
      timeoutSeconds: 0
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - ACTOKEY
        - ACTOKEY
        drop:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      privileged: false
      procMount: ACTOKEY
      readOnlyRootFilesystem: false
      runAsGroup: 3
      runAsNonRoot: false
      runAsUser: 0
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: ACTOKEY
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: ACTOKEY
        gmsaCredentialSpecName: ACTOKEY
        runAsUserName: ACTOKEY
    startupProbe:
      exec:
        command:
        - ACTOKEY
      failureThreshold: 3
      httpGet:
        host: ACTOKEY
        httpHeaders: null
        path: ACTOKEY
        port: 0
        scheme: ACTOKEY
      initialDelaySeconds: 5
      periodSeconds: 0
      successThreshold: 3
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      timeoutSeconds: 4
    stdin: true
    stdinOnce: true
    terminationMessagePath: null
    terminationMessagePolicy: ACTOKEY
    tty: false
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts: null
    workingDir: ACTOKEY
  - args:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    command:
    - ACTOKEY
    - ACTOKEY
    env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '.46'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: null
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 1
          resource: ACTOKEY
        secretKeyRef: null
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 4
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: null
          optional: false
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef: null
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: -.15270M
          resource: ACTOKEY
        secretKeyRef: null
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '.956999e+7583'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    envFrom:
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    - configMapRef:
        name: ACTOKEY
        optional: false
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: true
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    - configMapRef: null
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    image: ACTOKEY
    imagePullPolicy: null
    lifecycle:
      postStart:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        httpGet:
          host: null
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 3
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
      preStop:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 4
          scheme: null
        tcpSocket: null
    livenessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 0
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 3
        scheme: ACTOKEY
      initialDelaySeconds: 5
      periodSeconds: 2
      successThreshold: 3
      tcpSocket:
        host: null
        port: 2
      timeoutSeconds: 4
    name: ACTOKEY
    ports: []
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 0
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 3
      periodSeconds: 2
      successThreshold: 1
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      timeoutSeconds: null
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        drop: []
      privileged: true
      procMount: ACTOKEY
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 1
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: ACTOKEY
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: ACTOKEY
        gmsaCredentialSpecName: null
        runAsUserName: ACTOKEY
    startupProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: null
      httpGet:
        host: ACTOKEY
        httpHeaders: null
        path: ACTOKEY
        port: 1
        scheme: ACTOKEY
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 5
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      timeoutSeconds: 0
    stdin: false
    stdinOnce: true
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: true
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts:
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: true
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    workingDir: ACTOKEY
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  replicas: 3
  storageType: persistence
