apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  containers:
  - args:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    command:
    - ACTOKEY
    - ACTOKEY
    env:
    - name: ACTOKEY
      value: null
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef: null
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '.33'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    envFrom:
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart: null
      preStop:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 2
          scheme: ACTOKEY
        tcpSocket: null
    livenessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 1
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 1
        scheme: ACTOKEY
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 3
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      timeoutSeconds: 0
    name: ACTOKEY
    ports:
    - containerPort: 1
      hostIP: ACTOKEY
      hostPort: 4
      name: ACTOKEY
      protocol: ACTOKEY
    - containerPort: 0
      hostIP: ACTOKEY
      hostPort: 1
      name: ACTOKEY
      protocol: ACTOKEY
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 5
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 0
        scheme: ACTOKEY
      initialDelaySeconds: 3
      periodSeconds: 1
      successThreshold: 4
      tcpSocket: null
      timeoutSeconds: 3
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: null
      privileged: true
      procMount: ACTOKEY
      readOnlyRootFilesystem: false
      runAsGroup: 3
      runAsNonRoot: null
      runAsUser: 5
      seLinuxOptions: null
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions: null
    startupProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 3
      httpGet: null
      initialDelaySeconds: 2
      periodSeconds: 2
      successThreshold: 2
      tcpSocket: null
      timeoutSeconds: null
    stdin: null
    stdinOnce: true
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: false
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts:
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: true
      subPath: ACTOKEY
      subPathExpr: null
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: true
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    workingDir: ACTOKEY
  - args: null
    command:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: null
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 5
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: null
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: .1561850104e542763
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef: null
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef: null
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom: null
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 5
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    envFrom:
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: true
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef: null
    - configMapRef: null
      prefix: ACTOKEY
      secretRef:
        name: null
        optional: true
    - configMapRef:
        name: ACTOKEY
        optional: false
      prefix: null
      secretRef:
        name: ACTOKEY
        optional: true
    - configMapRef:
        name: ACTOKEY
        optional: false
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
      preStop:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: 2
    livenessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 1
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 2
        scheme: ACTOKEY
      initialDelaySeconds: 4
      periodSeconds: 3
      successThreshold: 5
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      timeoutSeconds: 3
    name: ACTOKEY
    ports:
    - containerPort: 4
      hostIP: ACTOKEY
      hostPort: 3
      name: ACTOKEY
      protocol: ACTOKEY
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 2
      httpGet:
        host: null
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        host: ACTOKEY
        port: 2
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: null
      privileged: true
      procMount: ACTOKEY
      readOnlyRootFilesystem: true
      runAsGroup: 3
      runAsNonRoot: false
      runAsUser: null
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: ACTOKEY
      seccompProfile:
        localhostProfile: null
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: null
        gmsaCredentialSpecName: ACTOKEY
        runAsUserName: ACTOKEY
    startupProbe:
      exec:
        command:
        - ACTOKEY
      failureThreshold: 3
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: null
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 5
      periodSeconds: null
      successThreshold: 4
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      timeoutSeconds: null
    stdin: false
    stdinOnce: false
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: true
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts:
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: null
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: null
      subPathExpr: ACTOKEY
    workingDir: null
  - args:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    command:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: null
          divisor: 5
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: null
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '.4703'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 4
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 0
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: null
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: .8812925929T
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    envFrom: []
    image: null
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart: null
      preStop:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: null
          port: 0
          scheme: ACTOKEY
        tcpSocket:
          host: ACTOKEY
          port: 5
    livenessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 5
      httpGet:
        host: ACTOKEY
        httpHeaders: null
        path: ACTOKEY
        port: 4
        scheme: ACTOKEY
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      tcpSocket:
        host: ACTOKEY
        port: 3
      timeoutSeconds: 3
    name: ACTOKEY
    ports:
    - containerPort: 0
      hostIP: ACTOKEY
      hostPort: 2
      name: null
      protocol: ACTOKEY
    - containerPort: 1
      hostIP: ACTOKEY
      hostPort: 1
      name: ACTOKEY
      protocol: ACTOKEY
    - containerPort: 1
      hostIP: ACTOKEY
      hostPort: 1
      name: ACTOKEY
      protocol: ACTOKEY
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 3
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 1
        scheme: ACTOKEY
      initialDelaySeconds: 2
      periodSeconds: 4
      successThreshold: 5
      tcpSocket: null
      timeoutSeconds: 3
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - ACTOKEY
        drop:
        - ACTOKEY
      privileged: false
      procMount: ACTOKEY
      readOnlyRootFilesystem: true
      runAsGroup: 4
      runAsNonRoot: null
      runAsUser: 1
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: ACTOKEY
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: ACTOKEY
        gmsaCredentialSpecName: ACTOKEY
        runAsUserName: ACTOKEY
    startupProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 5
      httpGet: null
      initialDelaySeconds: 5
      periodSeconds: 0
      successThreshold: null
      tcpSocket:
        host: ACTOKEY
        port: 2
      timeoutSeconds: 4
    stdin: true
    stdinOnce: true
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: true
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts: []
    workingDir: ACTOKEY
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  replicas: 3
  storageType: persistence
