apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: test-cluster
spec:
  additionalArgs:
  - ACTOKEY
  additionalLabels:
    crdb: is-cool
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v21.2.10
  ingress:
    ui:
      annotations:
        ACTOKEY: ACTOKEY
      host: ACTOKEY
      ingressClassName: ACTOKEY
      tls:
      - hosts: []
        secretName: ACTOKEY
      - hosts:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        secretName: null
      - hosts: null
        secretName: null
  nodes: 3
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  tlsEnabled: true
