apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: test-cluster
spec:
  clusterName: cluster1
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M
  managementApiAuth:
    insecure: {}
  podTemplateSpec:
    spec:
      containers:
      - name: ACTOKEY
      - name: ACTOKEY
      - name: ACTOKEY
      - name: ACTOKEY
      volumes:
      - awsElasticBlockStore:
          fsType: ACTOKEY
          partition: 3
          readOnly: true
          volumeID: ACTOKEY
        azureDisk:
          cachingMode: ACTOKEY
          diskName: ACTOKEY
          diskURI: ACTOKEY
          fsType: ACTOKEY
          kind: ACTOKEY
          readOnly: true
        azureFile:
          readOnly: null
          secretName: ACTOKEY
          shareName: ACTOKEY
        cephfs:
          monitors: []
          path: null
          readOnly: false
          secretFile: null
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        cinder:
          fsType: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          volumeID: ACTOKEY
        configMap:
          defaultMode: 0
          items:
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          name: ACTOKEY
          optional: null
        csi:
          driver: ACTOKEY
          fsType: ACTOKEY
          nodePublishSecretRef:
            name: ACTOKEY
          readOnly: true
          volumeAttributes:
            ACTOKEY: ACTOKEY
        downwardAPI:
          defaultMode: 1
          items:
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 1
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 3
              resource: ACTOKEY
        emptyDir:
          medium: ACTOKEY
          sizeLimit: 5
        ephemeral:
          volumeClaimTemplate:
            metadata:
              annotations:
                ACTOKEY: ACTOKEY
              finalizers: null
              labels:
                ACTOKEY: ACTOKEY
              name: ACTOKEY
              namespace: ACTOKEY
            spec:
              accessModes:
              - ACTOKEY
              - ACTOKEY
              dataSource:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              dataSourceRef:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              resources:
                limits:
                  ACTOKEY: '466310'
                requests:
                  ACTOKEY: 3
              selector:
                matchExpressions: null
                matchLabels:
                  ACTOKEY: ACTOKEY
              storageClassName: null
              volumeMode: ACTOKEY
              volumeName: ACTOKEY
        fc:
          fsType: null
          lun: 0
          readOnly: true
          targetWWNs:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          wwids:
          - ACTOKEY
        flexVolume:
          driver: ACTOKEY
          fsType: ACTOKEY
          options: null
          readOnly: true
          secretRef:
            name: ACTOKEY
        flocker:
          datasetName: ACTOKEY
          datasetUUID: ACTOKEY
        gcePersistentDisk:
          fsType: ACTOKEY
          partition: null
          pdName: ACTOKEY
          readOnly: true
        gitRepo:
          directory: ACTOKEY
          repository: ACTOKEY
          revision: ACTOKEY
        glusterfs:
          endpoints: ACTOKEY
          path: ACTOKEY
          readOnly: false
        hostPath: null
        iscsi:
          chapAuthDiscovery: true
          chapAuthSession: true
          fsType: ACTOKEY
          initiatorName: ACTOKEY
          iqn: ACTOKEY
          iscsiInterface: ACTOKEY
          lun: 2
          portals:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          readOnly: false
          secretRef:
            name: ACTOKEY
          targetPortal: ACTOKEY
        name: ACTOKEY
        nfs:
          path: ACTOKEY
          readOnly: true
          server: ACTOKEY
        persistentVolumeClaim:
          claimName: ACTOKEY
          readOnly: false
        photonPersistentDisk: null
        portworxVolume:
          fsType: ACTOKEY
          readOnly: true
          volumeID: ACTOKEY
        projected: null
        quobyte:
          group: ACTOKEY
          readOnly: false
          registry: ACTOKEY
          tenant: ACTOKEY
          user: ACTOKEY
          volume: ACTOKEY
        rbd:
          fsType: ACTOKEY
          image: ACTOKEY
          keyring: null
          monitors:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          pool: ACTOKEY
          readOnly: null
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        scaleIO:
          fsType: ACTOKEY
          gateway: ACTOKEY
          protectionDomain: ACTOKEY
          readOnly: null
          secretRef:
            name: ACTOKEY
          sslEnabled: false
          storageMode: ACTOKEY
          storagePool: ACTOKEY
          system: ACTOKEY
          volumeName: ACTOKEY
        secret:
          defaultMode: 4
          items:
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          optional: true
          secretName: ACTOKEY
        storageos:
          fsType: ACTOKEY
          readOnly: false
          secretRef:
            name: ACTOKEY
          volumeName: ACTOKEY
          volumeNamespace: ACTOKEY
        vsphereVolume:
          fsType: ACTOKEY
          storagePolicyID: ACTOKEY
          storagePolicyName: null
          volumePath: ACTOKEY
      - awsElasticBlockStore:
          fsType: null
          partition: 4
          readOnly: true
          volumeID: ACTOKEY
        azureDisk:
          cachingMode: ACTOKEY
          diskName: ACTOKEY
          diskURI: ACTOKEY
          fsType: ACTOKEY
          kind: ACTOKEY
          readOnly: true
        azureFile:
          readOnly: false
          secretName: ACTOKEY
          shareName: ACTOKEY
        cephfs:
          monitors: []
          path: ACTOKEY
          readOnly: true
          secretFile: null
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        cinder:
          fsType: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          volumeID: ACTOKEY
        configMap:
          defaultMode: 2
          items:
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        csi:
          driver: ACTOKEY
          fsType: ACTOKEY
          nodePublishSecretRef:
            name: ACTOKEY
          readOnly: false
          volumeAttributes: null
        downwardAPI:
          defaultMode: 5
          items:
          - fieldRef:
              apiVersion: null
              fieldPath: ACTOKEY
            mode: 4
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 2
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: null
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: .115T
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 0
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 2
              resource: ACTOKEY
        emptyDir: null
        ephemeral:
          volumeClaimTemplate:
            metadata: null
            spec:
              accessModes: []
              dataSource:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              dataSourceRef:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              resources:
                limits:
                  ACTOKEY: '.30403'
                requests:
                  ACTOKEY: 5
              selector:
                matchExpressions: []
                matchLabels:
                  ACTOKEY: ACTOKEY
              storageClassName: null
              volumeMode: ACTOKEY
              volumeName: ACTOKEY
        fc:
          fsType: ACTOKEY
          lun: 4
          readOnly: true
          targetWWNs:
          - ACTOKEY
          - ACTOKEY
          wwids:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        flexVolume:
          driver: ACTOKEY
          fsType: null
          options:
            ACTOKEY: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
        flocker:
          datasetName: ACTOKEY
          datasetUUID: ACTOKEY
        gcePersistentDisk:
          fsType: ACTOKEY
          partition: null
          pdName: ACTOKEY
          readOnly: false
        gitRepo:
          directory: ACTOKEY
          repository: ACTOKEY
          revision: ACTOKEY
        glusterfs:
          endpoints: ACTOKEY
          path: ACTOKEY
          readOnly: false
        hostPath:
          path: ACTOKEY
          type: ACTOKEY
        iscsi:
          chapAuthDiscovery: false
          chapAuthSession: false
          fsType: ACTOKEY
          initiatorName: ACTOKEY
          iqn: ACTOKEY
          iscsiInterface: ACTOKEY
          lun: 2
          portals:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          readOnly: true
          secretRef: null
          targetPortal: ACTOKEY
        name: ACTOKEY
        nfs:
          path: ACTOKEY
          readOnly: false
          server: ACTOKEY
        persistentVolumeClaim: null
        photonPersistentDisk:
          fsType: ACTOKEY
          pdID: ACTOKEY
        portworxVolume:
          fsType: ACTOKEY
          readOnly: true
          volumeID: ACTOKEY
        projected:
          defaultMode: 5
          sources: []
        quobyte:
          group: ACTOKEY
          readOnly: null
          registry: ACTOKEY
          tenant: null
          user: ACTOKEY
          volume: ACTOKEY
        rbd:
          fsType: ACTOKEY
          image: ACTOKEY
          keyring: ACTOKEY
          monitors:
          - ACTOKEY
          pool: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        scaleIO:
          fsType: ACTOKEY
          gateway: ACTOKEY
          protectionDomain: ACTOKEY
          readOnly: true
          secretRef:
            name: null
          sslEnabled: false
          storageMode: ACTOKEY
          storagePool: ACTOKEY
          system: ACTOKEY
          volumeName: ACTOKEY
        secret:
          defaultMode: 4
          items:
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          optional: false
          secretName: ACTOKEY
        storageos:
          fsType: ACTOKEY
          readOnly: false
          secretRef:
            name: ACTOKEY
          volumeName: ACTOKEY
          volumeNamespace: ACTOKEY
        vsphereVolume:
          fsType: ACTOKEY
          storagePolicyID: null
          storagePolicyName: ACTOKEY
          volumePath: ACTOKEY
      - awsElasticBlockStore:
          fsType: ACTOKEY
          partition: 4
          readOnly: false
          volumeID: ACTOKEY
        azureDisk:
          cachingMode: ACTOKEY
          diskName: ACTOKEY
          diskURI: ACTOKEY
          fsType: ACTOKEY
          kind: ACTOKEY
          readOnly: true
        azureFile:
          readOnly: false
          secretName: ACTOKEY
          shareName: ACTOKEY
        cephfs:
          monitors:
          - ACTOKEY
          - ACTOKEY
          path: ACTOKEY
          readOnly: true
          secretFile: ACTOKEY
          secretRef:
            name: ACTOKEY
          user: null
        cinder: null
        configMap:
          defaultMode: null
          items:
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        csi:
          driver: ACTOKEY
          fsType: null
          nodePublishSecretRef:
            name: ACTOKEY
          readOnly: true
          volumeAttributes:
            ACTOKEY: ACTOKEY
        downwardAPI:
          defaultMode: 1
          items:
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 2
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: '2357195.424601'
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 3
            path: ACTOKEY
            resourceFieldRef: null
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 5
            path: ACTOKEY
            resourceFieldRef: null
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 2
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 1
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 0
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: -.3449e+.845610
              resource: ACTOKEY
        emptyDir:
          medium: ACTOKEY
          sizeLimit: 3
        ephemeral:
          volumeClaimTemplate:
            metadata:
              annotations:
                ACTOKEY: ACTOKEY
              finalizers:
              - ACTOKEY
              - ACTOKEY
              labels:
                ACTOKEY: ACTOKEY
              name: ACTOKEY
              namespace: ACTOKEY
            spec:
              accessModes: []
              dataSource:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              dataSourceRef:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              resources:
                limits:
                  ACTOKEY: 1
                requests:
                  ACTOKEY: 0
              selector:
                matchExpressions:
                - key: ACTOKEY
                  operator: ACTOKEY
                  values: []
                - key: ACTOKEY
                  operator: ACTOKEY
                  values:
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                - key: ACTOKEY
                  operator: ACTOKEY
                  values:
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                - key: ACTOKEY
                  operator: ACTOKEY
                  values:
                  - ACTOKEY
                - key: ACTOKEY
                  operator: ACTOKEY
                  values:
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                matchLabels:
                  ACTOKEY: ACTOKEY
              storageClassName: ACTOKEY
              volumeMode: ACTOKEY
              volumeName: ACTOKEY
        fc:
          fsType: ACTOKEY
          lun: 1
          readOnly: false
          targetWWNs:
          - ACTOKEY
          - ACTOKEY
          wwids:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        flexVolume:
          driver: ACTOKEY
          fsType: null
          options:
            ACTOKEY: ACTOKEY
          readOnly: null
          secretRef:
            name: ACTOKEY
        flocker:
          datasetName: ACTOKEY
          datasetUUID: ACTOKEY
        gcePersistentDisk:
          fsType: ACTOKEY
          partition: 0
          pdName: ACTOKEY
          readOnly: true
        gitRepo:
          directory: ACTOKEY
          repository: ACTOKEY
          revision: null
        glusterfs:
          endpoints: ACTOKEY
          path: ACTOKEY
          readOnly: true
        hostPath:
          path: ACTOKEY
          type: ACTOKEY
        iscsi:
          chapAuthDiscovery: true
          chapAuthSession: false
          fsType: ACTOKEY
          initiatorName: ACTOKEY
          iqn: ACTOKEY
          iscsiInterface: ACTOKEY
          lun: 2
          portals: []
          readOnly: null
          secretRef:
            name: ACTOKEY
          targetPortal: ACTOKEY
        name: ACTOKEY
        nfs:
          path: ACTOKEY
          readOnly: true
          server: ACTOKEY
        persistentVolumeClaim: null
        photonPersistentDisk: null
        portworxVolume: null
        projected:
          defaultMode: 1
          sources: []
        quobyte:
          group: null
          readOnly: false
          registry: ACTOKEY
          tenant: null
          user: ACTOKEY
          volume: ACTOKEY
        rbd:
          fsType: ACTOKEY
          image: ACTOKEY
          keyring: ACTOKEY
          monitors:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          pool: null
          readOnly: false
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        scaleIO:
          fsType: ACTOKEY
          gateway: ACTOKEY
          protectionDomain: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          sslEnabled: true
          storageMode: ACTOKEY
          storagePool: null
          system: ACTOKEY
          volumeName: ACTOKEY
        secret:
          defaultMode: null
          items:
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          optional: false
          secretName: ACTOKEY
        storageos:
          fsType: null
          readOnly: false
          secretRef:
            name: ACTOKEY
          volumeName: ACTOKEY
          volumeNamespace: ACTOKEY
        vsphereVolume:
          fsType: ACTOKEY
          storagePolicyID: ACTOKEY
          storagePolicyName: ACTOKEY
          volumePath: ACTOKEY
  serverType: cassandra
  serverVersion: 3.11.7
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: server-storage
