apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  replicas: 3
  storageType: persistence
  volumes:
  - awsElasticBlockStore:
      fsType: ACTOKEY
      partition: 4
      readOnly: null
      volumeID: ACTOKEY
    azureDisk: null
    azureFile:
      readOnly: true
      secretName: ACTOKEY
      shareName: ACTOKEY
    cephfs:
      monitors: []
      path: ACTOKEY
      readOnly: false
      secretFile: ACTOKEY
      secretRef:
        name: ACTOKEY
      user: ACTOKEY
    cinder:
      fsType: ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
      volumeID: ACTOKEY
    configMap:
      defaultMode: 2
      items: []
      name: ACTOKEY
      optional: false
    csi:
      driver: ACTOKEY
      fsType: ACTOKEY
      nodePublishSecretRef: null
      readOnly: false
      volumeAttributes:
        ACTOKEY: ACTOKEY
    downwardAPI:
      defaultMode: 5
      items:
      - fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        mode: 0
        path: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 2
          resource: ACTOKEY
    emptyDir:
      medium: ACTOKEY
      sizeLimit: -86E
    ephemeral: null
    fc: null
    flexVolume:
      driver: ACTOKEY
      fsType: ACTOKEY
      options:
        ACTOKEY: ACTOKEY
      readOnly: true
      secretRef:
        name: ACTOKEY
    flocker:
      datasetName: ACTOKEY
      datasetUUID: ACTOKEY
    gcePersistentDisk:
      fsType: ACTOKEY
      partition: 5
      pdName: ACTOKEY
      readOnly: true
    gitRepo:
      directory: ACTOKEY
      repository: ACTOKEY
      revision: ACTOKEY
    glusterfs:
      endpoints: ACTOKEY
      path: ACTOKEY
      readOnly: true
    hostPath:
      path: ACTOKEY
      type: ACTOKEY
    iscsi:
      chapAuthDiscovery: true
      chapAuthSession: false
      fsType: ACTOKEY
      initiatorName: ACTOKEY
      iqn: ACTOKEY
      iscsiInterface: ACTOKEY
      lun: 1
      portals:
      - ACTOKEY
      readOnly: true
      secretRef:
        name: ACTOKEY
      targetPortal: ACTOKEY
    name: ACTOKEY
    nfs:
      path: ACTOKEY
      readOnly: false
      server: ACTOKEY
    persistentVolumeClaim:
      claimName: ACTOKEY
      readOnly: true
    photonPersistentDisk:
      fsType: ACTOKEY
      pdID: ACTOKEY
    portworxVolume:
      fsType: null
      readOnly: null
      volumeID: ACTOKEY
    projected:
      defaultMode: 5
      sources:
      - configMap:
          items:
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        downwardAPI:
          items:
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 1
            path: ACTOKEY
            resourceFieldRef: null
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 4
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 5
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 2
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: .0205e.0113
              resource: ACTOKEY
        secret:
          items:
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 0
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        downwardAPI:
          items:
          - fieldRef: null
            mode: 0
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: .3711437531m
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 0
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 0
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 1
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: .21u
              resource: ACTOKEY
        secret:
          items: null
          name: ACTOKEY
          optional: false
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 3
          path: ACTOKEY
      - configMap:
          items: []
          name: ACTOKEY
          optional: false
        downwardAPI:
          items: []
        secret:
          items:
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          name: ACTOKEY
          optional: null
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: null
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          name: null
          optional: false
        downwardAPI:
          items: []
        secret:
          items:
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 1
          path: ACTOKEY
    quobyte:
      group: ACTOKEY
      readOnly: true
      registry: ACTOKEY
      tenant: null
      user: ACTOKEY
      volume: ACTOKEY
    rbd:
      fsType: null
      image: ACTOKEY
      keyring: ACTOKEY
      monitors:
      - ACTOKEY
      pool: ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
      user: ACTOKEY
    scaleIO:
      fsType: ACTOKEY
      gateway: ACTOKEY
      protectionDomain: ACTOKEY
      readOnly: true
      secretRef:
        name: ACTOKEY
      sslEnabled: true
      storageMode: ACTOKEY
      storagePool: ACTOKEY
      system: ACTOKEY
      volumeName: ACTOKEY
    secret: null
    storageos:
      fsType: ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
      volumeName: ACTOKEY
      volumeNamespace: ACTOKEY
    vsphereVolume:
      fsType: ACTOKEY
      storagePolicyID: ACTOKEY
      storagePolicyName: ACTOKEY
      volumePath: ACTOKEY
