apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: test-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  sidecars:
  - env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom: null
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '5635.151797436'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: null
          divisor: 1
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef: null
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '.285921'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    name: ACTOKEY
    resources:
      limits:
        cpu: 800m
      requests:
        cpu: 800m
  - env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef: null
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: .22431E.92601
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: null
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 3
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef: null
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 4
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef: null
        fieldRef: null
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '.7402978100'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    name: ACTOKEY
    resources:
      limits:
        cpu: 800m
      requests:
        cpu: 800m
  - env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: null
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 1
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '8673'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 5
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: null
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: .8411E44
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef: null
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    name: ACTOKEY
    resources:
      limits:
        cpu: 800m
      requests:
        cpu: 800m
  - env:
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 1
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    name: ACTOKEY
    resources:
      limits:
        cpu: 800m
      requests:
        cpu: 800m
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
