apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq-system
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: null
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-cluster
        topologyKey: kubernetes.io/hostname
  image: null
  imagePullSecrets: null
  override:
    service:
      metadata:
        annotations:
          ACTOKEY: ACTOKEY
        labels:
          ACTOKEY: ACTOKEY
      spec:
        allocateLoadBalancerNodePorts: true
        clusterIP: ACTOKEY
        clusterIPs: []
        externalIPs:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        externalName: ACTOKEY
        externalTrafficPolicy: ACTOKEY
        healthCheckNodePort: 0
        internalTrafficPolicy: ACTOKEY
        ipFamilies: null
        ipFamilyPolicy: ACTOKEY
        loadBalancerClass: ACTOKEY
        loadBalancerIP: ACTOKEY
        loadBalancerSourceRanges:
        - ACTOKEY
        ports:
        - appProtocol: ACTOKEY
          name: ACTOKEY
          nodePort: 4
          port: 4
          protocol: ACTOKEY
          targetPort: 2
        - appProtocol: null
          name: ACTOKEY
          nodePort: 5
          port: 0
          protocol: ACTOKEY
          targetPort: ACTOKEY
        publishNotReadyAddresses: true
        selector:
          ACTOKEY: ACTOKEY
        sessionAffinity: ACTOKEY
        sessionAffinityConfig: null
        topologyKeys: []
        type: LoadBalancer
    statefulSet:
      spec:
        volumeClaimTemplates: []
  persistence:
    storage: 50Gi
  rabbitmq:
    additionalConfig: 'cluster_partition_handling = pause_minority

      vm_memory_high_watermark_paging_ratio = 0.99

      disk_free_limit.relative = 1.0

      collect_statistics_interval = 10000

      '
  replicas: 3
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  secretBackend:
    vault:
      annotations:
        ACTOKEY: ''
  service:
    type: ClusterIP
  skipPostDeploySteps: false
  terminationGracePeriodSeconds: 1024
  tls:
    caSecretName: null
    disableNonTLSListeners: false
    secretName: null
  tolerations: null
