apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: test-cluster
  namespace: knative-serving
spec:
  config:
    config-autoscaler:
      key1: value1
    network:
      ingress-class: kourier.ingress.networking.knative.dev
  deployments:
  - env:
    - container: controller
      envVars:
      - name: ENVAR_1
        value: VALUE_1
    name: controller
    resources:
    - container: controller
      limits:
        cpu: 950m
        memory: 250Mi
      requests:
        cpu: 300m
        memory: 125Mi
  ingress:
    kourier:
      enabled: true
  podDisruptionBudgets:
  - minAvailable: 50%
    name: activator-pdb
  - minAvailable: 50%
    name: webhook-pdb
  registry: {}
  services:
  - name: webhook
  version: 1.6.0
