apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: test-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: true
    env:
    - name: ACTOKEY
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisLeader:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
              - kind-worker2
              - kind-worker3kind-control-plane
    livenessProbe:
      exec: null
      failureThreshold: 2
      grpc:
        port: 2
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 0
        scheme: ACTOKEY
      initialDelaySeconds: 3
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        host: ACTOKEY
        port: 2
      terminationGracePeriodSeconds: 5
      timeoutSeconds: 1
    pdb:
      enabled: true
      maxUnavailable: 1
      minAvailable: null
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 4
      grpc:
        port: 2
        service: ACTOKEY
      httpGet:
        host: ACTOKEY
        httpHeaders: []
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 0
      periodSeconds: null
      successThreshold: 4
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 0
      timeoutSeconds: null
    redisConfig:
      additionalRedisConfig: ACTOKEY
    replicas: 3
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
