apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: test-cluster
spec:
  redis:
    customConfig:
    - maxclients 100
    - hz 50
    - timeout 60
    - tcp-keepalive 60
    - client-output-buffer-limit normal 0 0 0
    - client-output-buffer-limit slave 1000000000 1000000000 0
    - client-output-buffer-limit pubsub 33554432 8388608 60
    exporter:
      enabled: true
    imagePullPolicy: IfNotPresent
    replicas: 3
  sentinel:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - us-west-1
            topologyKey: failure-domain.beta.kubernetes.io/zone
          weight: 95
    customConfig:
    - down-after-milliseconds 2000
    - failover-timeout 3000
    exporter:
      args:
      - ''
      enabled: true
      env:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: +25372189.21524e.545034
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
    imagePullPolicy: IfNotPresent
    replicas: 3
