apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: test-cluster
spec:
  clusterName: cluster1
  config:
    cassandra-yaml:
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 800M
      max_heap_size: 800M
  configBuilderResources:
    limits:
      cpu: 800m
      memory: 1000m
    requests:
      ACTOKEY: 1000m
      cpu: 1000m
      memory: 1000m
  managementApiAuth:
    insecure: {}
  serverType: cassandra
  serverVersion: 3.11.7
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: server-storage
