apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  config:
    additionalConfig:
      ACTOKEY: ACTOKEY
    autoPurgePurgeInterval: 4
    autoPurgeSnapRetainCount: 4
    commitLogCount: 1
    globalOutstandingLimit: 1
    initLimit: 0
    maxClientCnxns: null
    maxCnxns: 2
    maxSessionTimeout: 2
    minSessionTimeout: null
    preAllocSize: null
    quorumListenOnAllIPs: true
    snapCount: 4
    snapSizeLimitInKb: 2
    syncLimit: 0
    tickTime: 2
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  probes:
    livenessProbe:
      timeoutSeconds: 0
  replicas: 3
  storageType: persistence
