apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      sidecarVolumes:
      - awsElasticBlockStore: null
        azureDisk:
          cachingMode: ACTOKEY
          diskName: ACTOKEY
          diskURI: ACTOKEY
          fsType: ACTOKEY
          kind: ACTOKEY
          readOnly: true
        azureFile: null
        cephfs:
          monitors:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          path: ACTOKEY
          readOnly: true
          secretFile: ACTOKEY
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        cinder:
          fsType: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          volumeID: ACTOKEY
        configMap:
          defaultMode: 5
          items: null
          name: null
          optional: true
        csi:
          driver: ACTOKEY
          fsType: ACTOKEY
          nodePublishSecretRef:
            name: ACTOKEY
          readOnly: false
          volumeAttributes:
            ACTOKEY: ACTOKEY
        downwardAPI:
          defaultMode: 4
          items:
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 1
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 0
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 5
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: null
              resource: ACTOKEY
          - fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            mode: 2
            path: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: '-79225'
              resource: ACTOKEY
        emptyDir:
          medium: ACTOKEY
          sizeLimit: null
        ephemeral:
          volumeClaimTemplate:
            metadata: null
            spec:
              accessModes:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              dataSource:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              dataSourceRef:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              resources: null
              selector:
                matchExpressions:
                - key: ACTOKEY
                  operator: ACTOKEY
                  values: []
                - key: ACTOKEY
                  operator: ACTOKEY
                  values:
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                  - ACTOKEY
                - key: ACTOKEY
                  operator: ACTOKEY
                  values:
                  - ACTOKEY
                - key: ACTOKEY
                  operator: ACTOKEY
                  values: []
                matchLabels:
                  ACTOKEY: ACTOKEY
              storageClassName: ACTOKEY
              volumeMode: ACTOKEY
              volumeName: ACTOKEY
        fc:
          fsType: ACTOKEY
          lun: 0
          readOnly: true
          targetWWNs:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          wwids:
          - ACTOKEY
          - ACTOKEY
        flexVolume:
          driver: ACTOKEY
          fsType: ACTOKEY
          options:
            ACTOKEY: ACTOKEY
          readOnly: false
          secretRef:
            name: ACTOKEY
        flocker:
          datasetName: ACTOKEY
          datasetUUID: ACTOKEY
        gcePersistentDisk: null
        gitRepo:
          directory: ACTOKEY
          repository: ACTOKEY
          revision: ACTOKEY
        glusterfs:
          endpoints: ACTOKEY
          path: ACTOKEY
          readOnly: false
        hostPath:
          path: ACTOKEY
          type: ACTOKEY
        iscsi:
          chapAuthDiscovery: null
          chapAuthSession: false
          fsType: ACTOKEY
          initiatorName: ACTOKEY
          iqn: ACTOKEY
          iscsiInterface: null
          lun: 0
          portals:
          - ACTOKEY
          readOnly: null
          secretRef:
            name: ACTOKEY
          targetPortal: ACTOKEY
        name: ACTOKEY
        nfs:
          path: ACTOKEY
          readOnly: true
          server: ACTOKEY
        persistentVolumeClaim:
          claimName: ACTOKEY
          readOnly: true
        photonPersistentDisk:
          fsType: ACTOKEY
          pdID: ACTOKEY
        portworxVolume:
          fsType: ACTOKEY
          readOnly: false
          volumeID: ACTOKEY
        projected:
          defaultMode: 5
          sources:
          - configMap:
              items:
              - key: ACTOKEY
                mode: 1
                path: ACTOKEY
              - key: ACTOKEY
                mode: 4
                path: ACTOKEY
              - key: ACTOKEY
                mode: null
                path: ACTOKEY
              - key: ACTOKEY
                mode: 3
                path: ACTOKEY
              - key: ACTOKEY
                mode: 1
                path: ACTOKEY
              name: ACTOKEY
              optional: true
            downwardAPI: null
            secret:
              items:
              - key: ACTOKEY
                mode: null
                path: ACTOKEY
              - key: ACTOKEY
                mode: 2
                path: ACTOKEY
              name: ACTOKEY
              optional: true
            serviceAccountToken:
              audience: null
              expirationSeconds: 5
              path: ACTOKEY
          - configMap:
              items:
              - key: ACTOKEY
                mode: 1
                path: ACTOKEY
              - key: ACTOKEY
                mode: 1
                path: ACTOKEY
              - key: ACTOKEY
                mode: 3
                path: ACTOKEY
              - key: ACTOKEY
                mode: 5
                path: ACTOKEY
              - key: ACTOKEY
                mode: 0
                path: ACTOKEY
              name: ACTOKEY
              optional: true
            downwardAPI:
              items:
              - fieldRef:
                  apiVersion: ACTOKEY
                  fieldPath: ACTOKEY
                mode: 4
                path: ACTOKEY
                resourceFieldRef:
                  containerName: ACTOKEY
                  divisor: +.15719Pi
                  resource: ACTOKEY
            secret:
              items:
              - key: ACTOKEY
                mode: 1
                path: ACTOKEY
              - key: ACTOKEY
                mode: 5
                path: ACTOKEY
              name: ACTOKEY
              optional: true
            serviceAccountToken:
              audience: null
              expirationSeconds: 3
              path: ACTOKEY
          - configMap:
              items:
              - key: ACTOKEY
                mode: 2
                path: ACTOKEY
              - key: ACTOKEY
                mode: 3
                path: ACTOKEY
              name: ACTOKEY
              optional: false
            downwardAPI:
              items:
              - fieldRef:
                  apiVersion: ACTOKEY
                  fieldPath: ACTOKEY
                mode: 1
                path: ACTOKEY
                resourceFieldRef:
                  containerName: ACTOKEY
                  divisor: 6506884384P
                  resource: ACTOKEY
              - fieldRef:
                  apiVersion: ACTOKEY
                  fieldPath: ACTOKEY
                mode: 5
                path: ACTOKEY
                resourceFieldRef:
                  containerName: ACTOKEY
                  divisor: -.609058
                  resource: ACTOKEY
              - fieldRef:
                  apiVersion: ACTOKEY
                  fieldPath: ACTOKEY
                mode: 4
                path: ACTOKEY
                resourceFieldRef:
                  containerName: ACTOKEY
                  divisor: 1
                  resource: ACTOKEY
              - fieldRef: null
                mode: 3
                path: ACTOKEY
                resourceFieldRef:
                  containerName: ACTOKEY
                  divisor: 4
                  resource: ACTOKEY
            secret:
              items: null
              name: ACTOKEY
              optional: true
            serviceAccountToken:
              audience: ACTOKEY
              expirationSeconds: 2
              path: ACTOKEY
        quobyte:
          group: null
          readOnly: true
          registry: ACTOKEY
          tenant: ACTOKEY
          user: ACTOKEY
          volume: ACTOKEY
        rbd:
          fsType: ACTOKEY
          image: ACTOKEY
          keyring: ACTOKEY
          monitors:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          pool: ACTOKEY
          readOnly: false
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        scaleIO:
          fsType: ACTOKEY
          gateway: ACTOKEY
          protectionDomain: ACTOKEY
          readOnly: null
          secretRef:
            name: ACTOKEY
          sslEnabled: true
          storageMode: ACTOKEY
          storagePool: ACTOKEY
          system: ACTOKEY
          volumeName: ACTOKEY
        secret:
          defaultMode: null
          items:
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          optional: false
          secretName: ACTOKEY
        storageos:
          fsType: ACTOKEY
          readOnly: false
          secretRef:
            name: ACTOKEY
          volumeName: ACTOKEY
          volumeNamespace: ACTOKEY
        vsphereVolume:
          fsType: ACTOKEY
          storagePolicyID: ACTOKEY
          storagePolicyName: null
          volumePath: ACTOKEY
      - awsElasticBlockStore: null
        azureDisk:
          cachingMode: ACTOKEY
          diskName: ACTOKEY
          diskURI: ACTOKEY
          fsType: ACTOKEY
          kind: ACTOKEY
          readOnly: false
        azureFile:
          readOnly: false
          secretName: ACTOKEY
          shareName: ACTOKEY
        cephfs:
          monitors:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          path: null
          readOnly: false
          secretFile: ACTOKEY
          secretRef:
            name: ACTOKEY
          user: null
        cinder: null
        configMap:
          defaultMode: 3
          items: []
          name: ACTOKEY
          optional: true
        csi:
          driver: ACTOKEY
          fsType: ACTOKEY
          nodePublishSecretRef:
            name: ACTOKEY
          readOnly: false
          volumeAttributes:
            ACTOKEY: ACTOKEY
        downwardAPI:
          defaultMode: null
          items: []
        emptyDir:
          medium: null
          sizeLimit: +.962E.5
        ephemeral:
          volumeClaimTemplate:
            metadata: null
            spec:
              accessModes:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              dataSource:
                apiGroup: null
                kind: ACTOKEY
                name: ACTOKEY
              dataSourceRef:
                apiGroup: ACTOKEY
                kind: ACTOKEY
                name: ACTOKEY
              resources:
                limits:
                  ACTOKEY: +5017798882.5724Mi
                requests:
                  ACTOKEY: '46383026.470'
              selector:
                matchExpressions:
                - key: ACTOKEY
                  operator: ACTOKEY
                  values: []
                matchLabels:
                  ACTOKEY: ACTOKEY
              storageClassName: ACTOKEY
              volumeMode: ACTOKEY
              volumeName: ACTOKEY
        fc:
          fsType: ACTOKEY
          lun: 4
          readOnly: true
          targetWWNs:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          wwids: null
        flexVolume: null
        flocker:
          datasetName: null
          datasetUUID: ACTOKEY
        gcePersistentDisk:
          fsType: ACTOKEY
          partition: null
          pdName: ACTOKEY
          readOnly: false
        gitRepo: null
        glusterfs:
          endpoints: ACTOKEY
          path: ACTOKEY
          readOnly: true
        hostPath:
          path: ACTOKEY
          type: null
        iscsi:
          chapAuthDiscovery: false
          chapAuthSession: false
          fsType: ACTOKEY
          initiatorName: ACTOKEY
          iqn: ACTOKEY
          iscsiInterface: ACTOKEY
          lun: 5
          portals: []
          readOnly: false
          secretRef:
            name: null
          targetPortal: ACTOKEY
        name: ACTOKEY
        nfs: null
        persistentVolumeClaim:
          claimName: ACTOKEY
          readOnly: true
        photonPersistentDisk:
          fsType: null
          pdID: ACTOKEY
        portworxVolume:
          fsType: null
          readOnly: false
          volumeID: ACTOKEY
        projected:
          defaultMode: 1
          sources: []
        quobyte:
          group: ACTOKEY
          readOnly: null
          registry: ACTOKEY
          tenant: ACTOKEY
          user: ACTOKEY
          volume: ACTOKEY
        rbd:
          fsType: null
          image: ACTOKEY
          keyring: null
          monitors:
          - ACTOKEY
          - ACTOKEY
          pool: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        scaleIO:
          fsType: ACTOKEY
          gateway: ACTOKEY
          protectionDomain: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          sslEnabled: true
          storageMode: ACTOKEY
          storagePool: ACTOKEY
          system: ACTOKEY
          volumeName: ACTOKEY
        secret:
          defaultMode: 5
          items: null
          optional: true
          secretName: ACTOKEY
        storageos:
          fsType: ACTOKEY
          readOnly: null
          secretRef:
            name: ACTOKEY
          volumeName: ACTOKEY
          volumeNamespace: null
        vsphereVolume:
          fsType: ACTOKEY
          storagePolicyID: ACTOKEY
          storagePolicyName: ACTOKEY
          volumePath: ACTOKEY
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
