apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      sidecarVolumes:
      - awsElasticBlockStore:
          fsType: ACTOKEY
          partition: 5
          readOnly: false
          volumeID: ACTOKEY
        azureDisk:
          cachingMode: ACTOKEY
          diskName: ACTOKEY
          diskURI: ACTOKEY
          fsType: ACTOKEY
          kind: ACTOKEY
          readOnly: true
        azureFile:
          readOnly: null
          secretName: ACTOKEY
          shareName: ACTOKEY
        cephfs:
          monitors:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          path: ACTOKEY
          readOnly: true
          secretFile: ACTOKEY
          secretRef: null
          user: ACTOKEY
        cinder:
          fsType: ACTOKEY
          readOnly: false
          secretRef:
            name: null
          volumeID: ACTOKEY
        configMap:
          defaultMode: 3
          items:
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        csi:
          driver: ACTOKEY
          fsType: ACTOKEY
          nodePublishSecretRef:
            name: ACTOKEY
          readOnly: false
          volumeAttributes:
            ACTOKEY: ACTOKEY
        downwardAPI:
          defaultMode: null
          items: null
        emptyDir:
          medium: null
          sizeLimit: 3
        ephemeral:
          volumeClaimTemplate:
            metadata: null
            spec:
              accessModes:
              - ACTOKEY
              - ACTOKEY
              dataSource: null
              dataSourceRef: null
              resources:
                limits: null
                requests:
                  ACTOKEY: 5
              selector:
                matchExpressions: null
                matchLabels:
                  ACTOKEY: ACTOKEY
              storageClassName: ACTOKEY
              volumeMode: ACTOKEY
              volumeName: ACTOKEY
        fc:
          fsType: ACTOKEY
          lun: 5
          readOnly: false
          targetWWNs:
          - ACTOKEY
          wwids:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        flexVolume:
          driver: ACTOKEY
          fsType: ACTOKEY
          options:
            ACTOKEY: ACTOKEY
          readOnly: false
          secretRef:
            name: ACTOKEY
        flocker: null
        gcePersistentDisk:
          fsType: ACTOKEY
          partition: 4
          pdName: ACTOKEY
          readOnly: true
        gitRepo:
          directory: ACTOKEY
          repository: ACTOKEY
          revision: null
        glusterfs:
          endpoints: ACTOKEY
          path: ACTOKEY
          readOnly: true
        hostPath:
          path: ACTOKEY
          type: ACTOKEY
        iscsi:
          chapAuthDiscovery: false
          chapAuthSession: false
          fsType: ACTOKEY
          initiatorName: ACTOKEY
          iqn: ACTOKEY
          iscsiInterface: null
          lun: 1
          portals:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          readOnly: false
          secretRef:
            name: ACTOKEY
          targetPortal: ACTOKEY
        name: ACTOKEY
        nfs: null
        persistentVolumeClaim:
          claimName: ACTOKEY
          readOnly: true
        photonPersistentDisk:
          fsType: null
          pdID: ACTOKEY
        portworxVolume:
          fsType: ACTOKEY
          readOnly: false
          volumeID: ACTOKEY
        projected: null
        quobyte:
          group: null
          readOnly: null
          registry: ACTOKEY
          tenant: ACTOKEY
          user: ACTOKEY
          volume: ACTOKEY
        rbd:
          fsType: ACTOKEY
          image: ACTOKEY
          keyring: ACTOKEY
          monitors:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          pool: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          user: ACTOKEY
        scaleIO:
          fsType: ACTOKEY
          gateway: ACTOKEY
          protectionDomain: ACTOKEY
          readOnly: true
          secretRef:
            name: ACTOKEY
          sslEnabled: false
          storageMode: ACTOKEY
          storagePool: ACTOKEY
          system: ACTOKEY
          volumeName: ACTOKEY
        secret: null
        storageos:
          fsType: null
          readOnly: false
          secretRef:
            name: ACTOKEY
          volumeName: ACTOKEY
          volumeNamespace: null
        vsphereVolume:
          fsType: ACTOKEY
          storagePolicyID: ACTOKEY
          storagePolicyName: ACTOKEY
          volumePath: ACTOKEY
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
