apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  replicas: 3
  storageType: persistence
  volumeMounts:
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: false
    subPath: ACTOKEY
    subPathExpr: null
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: false
    subPath: null
    subPathExpr: ACTOKEY
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: false
    subPath: ACTOKEY
    subPathExpr: ACTOKEY
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: false
    subPath: ACTOKEY
    subPathExpr: ACTOKEY
  - mountPath: ACTOKEY
    mountPropagation: ACTOKEY
    name: ACTOKEY
    readOnly: false
    subPath: ACTOKEY
    subPathExpr: ACTOKEY
