apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  probes:
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 5
      periodSeconds: 1
      successThreshold: 2
      timeoutSeconds: 3
    readinessProbe:
      failureThreshold: 2
      initialDelaySeconds: 4
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 0
  replicas: 3
  storageType: persistence
