apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: test-cluster
spec:
  configUpdateStrategy: RollingUpdate
  enableDynamicConfiguration: true
  helper:
    image: busybox:1.34.1
  pd:
    baseImage: pingcap/pd
    config: "[dashboard]\n  internal-proxy = true\n"
    maxFailoverCount: 0
    mountClusterClientSecret: true
    replicas: 3
    requests:
      storage: 10Gi
  pvReclaimPolicy: Retain
  tidb:
    baseImage: pingcap/tidb
    config: "[performance]\n  tcp-keep-alive = true\n"
    initContainers:
    - args:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      command:
      - ACTOKEY
      - ACTOKEY
      env: []
      envFrom: null
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec: null
          httpGet:
            host: ACTOKEY
            httpHeaders: null
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: 3
        preStop:
          exec: null
          httpGet:
            host: ACTOKEY
            httpHeaders: []
            path: null
            port: 0
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: 2
      livenessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 2
        httpGet:
          host: ACTOKEY
          httpHeaders: null
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 3
        periodSeconds: 2
        successThreshold: 2
        tcpSocket: null
        timeoutSeconds: 2
      name: ACTOKEY
      ports:
      - containerPort: 4
        hostIP: ACTOKEY
        hostPort: 5
        name: ACTOKEY
        protocol: ACTOKEY
      - containerPort: 2
        hostIP: ACTOKEY
        hostPort: 3
        name: ACTOKEY
        protocol: ACTOKEY
      - containerPort: 5
        hostIP: null
        hostPort: 4
        name: ACTOKEY
        protocol: ACTOKEY
      readinessProbe:
        exec:
          command: []
        failureThreshold: 4
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 4
        periodSeconds: 5
        successThreshold: null
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        timeoutSeconds: null
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add: []
          drop:
          - ACTOKEY
        privileged: false
        procMount: ACTOKEY
        readOnlyRootFilesystem: false
        runAsGroup: 3
        runAsNonRoot: false
        runAsUser: 2
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile:
          localhostProfile: null
          type: ACTOKEY
        windowsOptions:
          gmsaCredentialSpec: ACTOKEY
          gmsaCredentialSpecName: ACTOKEY
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 1
        httpGet:
          host: null
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 1
          scheme: ACTOKEY
        initialDelaySeconds: 0
        periodSeconds: 3
        successThreshold: 3
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        timeoutSeconds: 3
      stdin: true
      stdinOnce: false
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: null
      tty: true
      volumeDevices:
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      volumeMounts:
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: null
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: null
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: null
      workingDir: ACTOKEY
    - args: []
      command: null
      env:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: +.10895255m
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: null
            optional: false
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 2
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 3
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      envFrom:
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: true
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: null
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef:
          name: ACTOKEY
          optional: null
        prefix: null
        secretRef:
          name: ACTOKEY
          optional: true
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec:
            command: []
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: 0
        preStop:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: ACTOKEY
            scheme: null
          tcpSocket:
            host: ACTOKEY
            port: 3
      livenessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 1
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 0
          scheme: ACTOKEY
        initialDelaySeconds: 5
        periodSeconds: null
        successThreshold: 1
        tcpSocket:
          host: ACTOKEY
          port: 3
        timeoutSeconds: 4
      name: ACTOKEY
      ports:
      - containerPort: 5
        hostIP: ACTOKEY
        hostPort: 5
        name: ACTOKEY
        protocol: ACTOKEY
      readinessProbe:
        exec:
          command: []
        failureThreshold: 4
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 5
          scheme: null
        initialDelaySeconds: 0
        periodSeconds: 3
        successThreshold: 0
        tcpSocket:
          host: ACTOKEY
          port: 0
        timeoutSeconds: 2
      resources: null
      securityContext:
        allowPrivilegeEscalation: null
        capabilities:
          add:
          - ACTOKEY
          drop:
          - ACTOKEY
        privileged: false
        procMount: ACTOKEY
        readOnlyRootFilesystem: false
        runAsGroup: 4
        runAsNonRoot: true
        runAsUser: 3
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile:
          localhostProfile: ACTOKEY
          type: ACTOKEY
        windowsOptions:
          gmsaCredentialSpec: null
          gmsaCredentialSpecName: ACTOKEY
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command: []
        failureThreshold: 2
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 0
          scheme: null
        initialDelaySeconds: 1
        periodSeconds: 4
        successThreshold: 2
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        timeoutSeconds: 4
      stdin: false
      stdinOnce: true
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: ACTOKEY
      tty: true
      volumeDevices:
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      volumeMounts: []
      workingDir: ACTOKEY
    maxFailoverCount: 0
    replicas: 3
    service:
      externalTrafficPolicy: Local
      type: NodePort
    serviceAccount: ''
  tikv:
    baseImage: pingcap/tikv
    config: 'log-level = "info"

      '
    maxFailoverCount: 0
    mountClusterClientSecret: true
    recoverFailover: false
    replicas: 3
    requests:
      storage: 100Gi
    separateRaftLog: true
  timezone: UTC
  version: v5.4.0
