apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: test-cluster
spec:
  configUpdateStrategy: RollingUpdate
  enableDynamicConfiguration: true
  helper:
    image: busybox:1.34.1
  pd:
    baseImage: pingcap/pd
    config: "[dashboard]\n  internal-proxy = true\n"
    maxFailoverCount: 0
    mountClusterClientSecret: true
    replicas: 3
    requests:
      storage: 10Gi
  pvReclaimPolicy: Retain
  tidb:
    baseImage: pingcap/tidb
    config: "[performance]\n  tcp-keep-alive = true\n"
    initContainers:
    - args: []
      command:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      env:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 2
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef: null
          fieldRef:
            apiVersion: null
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 3
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 5
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
      envFrom:
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: true
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef: null
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          httpGet: null
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
        preStop: null
      livenessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 3
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 5
          scheme: ACTOKEY
        initialDelaySeconds: 1
        periodSeconds: 3
        successThreshold: 1
        tcpSocket:
          host: ACTOKEY
          port: 4
        timeoutSeconds: 0
      name: ACTOKEY
      ports:
      - containerPort: 5
        hostIP: ACTOKEY
        hostPort: 1
        name: ACTOKEY
        protocol: ACTOKEY
      - containerPort: 4
        hostIP: ACTOKEY
        hostPort: 3
        name: ACTOKEY
        protocol: null
      - containerPort: 4
        hostIP: null
        hostPort: 4
        name: ACTOKEY
        protocol: null
      - containerPort: 3
        hostIP: ACTOKEY
        hostPort: 4
        name: ACTOKEY
        protocol: ACTOKEY
      readinessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 2
        httpGet: null
        initialDelaySeconds: 3
        periodSeconds: 1
        successThreshold: 4
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          drop:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        privileged: true
        procMount: null
        readOnlyRootFilesystem: true
        runAsGroup: 4
        runAsNonRoot: null
        runAsUser: null
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile: null
        windowsOptions:
          gmsaCredentialSpec: ACTOKEY
          gmsaCredentialSpecName: ACTOKEY
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command: null
        failureThreshold: 0
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 3
          scheme: ACTOKEY
        initialDelaySeconds: 4
        periodSeconds: 2
        successThreshold: 5
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        timeoutSeconds: 3
      stdin: false
      stdinOnce: true
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: ACTOKEY
      tty: true
      volumeDevices:
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      volumeMounts: null
      workingDir: ACTOKEY
    maxFailoverCount: 0
    replicas: 3
    service:
      externalTrafficPolicy: Local
      type: NodePort
    serviceAccount: ''
  tikv:
    baseImage: pingcap/tikv
    config: 'log-level = "info"

      '
    maxFailoverCount: 0
    mountClusterClientSecret: true
    recoverFailover: false
    replicas: 3
    requests:
      storage: 100Gi
    separateRaftLog: true
  timezone: UTC
  version: v5.4.0
