apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: test-cluster
  namespace: knative-serving
spec:
  config:
    config-autoscaler:
      key1: value1
    network:
      ingress-class: kourier.ingress.networking.knative.dev
  deployments:
  - env:
    - container: controller
      envVars:
      - name: ENVAR_1
        value: VALUE_1
    name: controller
    resources:
    - container: controller
      limits:
        cpu: 950m
        memory: 250Mi
      requests:
        cpu: 300m
        memory: 125Mi
  - affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
              - kind-worker2
              - kind-worker3kind-control-plane
    annotations:
      ACTOKEY: ACTOKEY
    env:
    - container: ACTOKEY
      envVars:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: -.69620290Gi
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: +.48885Ei
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
    - container: ACTOKEY
      envVars:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 2
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: null
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: '.7'
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef: null
          secretKeyRef:
            key: ACTOKEY
            name: null
            optional: false
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 3
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
    labels:
      ACTOKEY: ACTOKEY
    name: ACTOKEY
    nodeSelector:
      ACTOKEY: ACTOKEY
    replicas: null
    resources:
    - container: ACTOKEY
      limits:
        cpu: -727820.92emEnTKGn-27808
        memory: null
      requests:
        cpu: null
        memory: 9597568TEime05
    - container: ACTOKEY
      limits:
        cpu: 60925k5994497
        memory: 43615110eikGP78771
      requests:
        cpu: -.EEmmEKei-
        memory: 2222..395+
    tolerations:
    - effect: NoSchedule
      key: test-key
      operator: Equal
      value: test-value
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
  ingress:
    kourier:
      enabled: true
  podDisruptionBudgets:
  - minAvailable: 50%
    name: activator-pdb
  - minAvailable: 50%
    name: webhook-pdb
  registry:
    default: gcr.io/knative-releases/knative.dev/serving/cmd/${NAME}:v1.6.0
    override:
      kourier-gateway: docker.io/envoyproxy/envoy:v1.20-latest
      migrate: gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate:latest
      net-kourier-controller/controller: gcr.io/knative-releases/knative.dev/net-kourier/cmd/kourier:v1.6.0
  services:
  - name: webhook
  version: 1.6.0
