apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq-system
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: null
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-cluster
        topologyKey: kubernetes.io/hostname
  image: null
  imagePullSecrets: null
  override:
    service:
      metadata: null
      spec:
        allocateLoadBalancerNodePorts: false
        clusterIP: ACTOKEY
        clusterIPs:
        - ACTOKEY
        externalIPs:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        externalName: ACTOKEY
        externalTrafficPolicy: ACTOKEY
        healthCheckNodePort: 1
        internalTrafficPolicy: ACTOKEY
        ipFamilies:
        - ACTOKEY
        - ACTOKEY
        ipFamilyPolicy: ACTOKEY
        loadBalancerClass: ACTOKEY
        loadBalancerIP: ACTOKEY
        loadBalancerSourceRanges:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        ports: null
        publishNotReadyAddresses: false
        selector:
          ACTOKEY: ACTOKEY
        sessionAffinity: ACTOKEY
        sessionAffinityConfig:
          clientIP:
            timeoutSeconds: 1
        topologyKeys: []
        type: LoadBalancer
    statefulSet: null
  persistence:
    storage: 50Gi
    storageClassName: ''
  rabbitmq:
    additionalConfig: 'cluster_partition_handling = pause_minority

      vm_memory_high_watermark_paging_ratio = 0.99

      disk_free_limit.relative = 1.0

      collect_statistics_interval = 10000

      '
  replicas: 3
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  secretBackend: null
  service:
    type: NodePort
  skipPostDeploySteps: false
  terminationGracePeriodSeconds: 1024
  tls:
    caSecretName: null
    disableNonTLSListeners: false
    secretName: null
  tolerations: null
