apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  clientService:
    annotations: {}
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  probes:
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 4
      periodSeconds: 4
      successThreshold: 0
      timeoutSeconds: 0
  replicas: 3
  storageType: persistence
