apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  initContainers:
  - args:
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    - ACTOKEY
    command: null
    env:
    - name: ACTOKEY
      value: null
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: 3
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: null
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: -.08160985T
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '+9603608'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    - name: ACTOKEY
      value: ACTOKEY
      valueFrom:
        configMapKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: false
        fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '+6529'
          resource: ACTOKEY
        secretKeyRef:
          key: ACTOKEY
          name: ACTOKEY
          optional: true
    envFrom:
    - configMapRef: null
      prefix: null
      secretRef:
        name: ACTOKEY
        optional: false
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: true
    - configMapRef:
        name: ACTOKEY
        optional: true
      prefix: ACTOKEY
      secretRef:
        name: ACTOKEY
        optional: false
    image: ACTOKEY
    imagePullPolicy: ACTOKEY
    lifecycle:
      postStart:
        exec: null
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        tcpSocket:
          host: null
          port: 3
      preStop: null
    livenessProbe:
      exec:
        command: []
      failureThreshold: 1
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 2
        scheme: ACTOKEY
      initialDelaySeconds: 2
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      timeoutSeconds: 4
    name: ACTOKEY
    ports: null
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 0
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 5
        scheme: ACTOKEY
      initialDelaySeconds: null
      periodSeconds: 5
      successThreshold: 5
      tcpSocket:
        host: ACTOKEY
        port: 0
      timeoutSeconds: 4
    resources:
      limits:
        cpu: 800m
        memory: 1000m
      requests:
        cpu: 800m
        memory: 1000m
    securityContext:
      allowPrivilegeEscalation: null
      capabilities:
        add:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        drop: []
      privileged: null
      procMount: ACTOKEY
      readOnlyRootFilesystem: null
      runAsGroup: 5
      runAsNonRoot: false
      runAsUser: 3
      seLinuxOptions:
        level: ACTOKEY
        role: ACTOKEY
        type: ACTOKEY
        user: ACTOKEY
      seccompProfile:
        localhostProfile: ACTOKEY
        type: ACTOKEY
      windowsOptions:
        gmsaCredentialSpec: ACTOKEY
        gmsaCredentialSpecName: null
        runAsUserName: ACTOKEY
    startupProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: null
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 0
        scheme: ACTOKEY
      initialDelaySeconds: 4
      periodSeconds: 5
      successThreshold: 3
      tcpSocket:
        host: null
        port: 3
      timeoutSeconds: null
    stdin: false
    stdinOnce: true
    terminationMessagePath: ACTOKEY
    terminationMessagePolicy: ACTOKEY
    tty: null
    volumeDevices:
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    - devicePath: ACTOKEY
      name: ACTOKEY
    volumeMounts:
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: null
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    - mountPath: ACTOKEY
      mountPropagation: ACTOKEY
      name: ACTOKEY
      readOnly: false
      subPath: ACTOKEY
      subPathExpr: ACTOKEY
    workingDir: ACTOKEY
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  replicas: 3
  storageType: persistence
