apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: test-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisLeader:
    pdb:
      enabled: true
      minAvailable: 0
    readinessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 0
      grpc:
        port: 2
        service: ACTOKEY
      httpGet:
        host: null
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: 0
        scheme: ACTOKEY
      initialDelaySeconds: 3
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        host: ACTOKEY
        port: ACTOKEY
      terminationGracePeriodSeconds: 4
      timeoutSeconds: 5
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
