apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      sidecars:
      - args:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        command:
        - ACTOKEY
        env:
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: true
            fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: '-62'
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
        envFrom:
        - configMapRef:
            name: ACTOKEY
            optional: true
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: null
        image: ACTOKEY
        imagePullPolicy: ACTOKEY
        lifecycle:
          postStart: null
          preStop:
            exec:
              command:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            httpGet:
              host: ACTOKEY
              httpHeaders:
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              path: ACTOKEY
              port: 2
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: 1
        livenessProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 3
          grpc:
            port: 0
            service: ACTOKEY
          httpGet: null
          initialDelaySeconds: 2
          periodSeconds: 3
          successThreshold: 3
          tcpSocket: null
          terminationGracePeriodSeconds: 3
          timeoutSeconds: 5
        name: ACTOKEY
        ports:
        - containerPort: 5
          hostIP: ACTOKEY
          hostPort: 1
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 1
          hostIP: ACTOKEY
          hostPort: 5
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 3
          hostIP: ACTOKEY
          hostPort: 3
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 5
          hostIP: ACTOKEY
          hostPort: 0
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 1
          hostIP: null
          hostPort: 0
          name: ACTOKEY
          protocol: ACTOKEY
        readinessProbe: null
        resources:
          limits:
            cpu: 800m
            memory: 1000m
          requests:
            cpu: 800m
            memory: 1000m
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: []
            drop:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          privileged: true
          procMount: ACTOKEY
          readOnlyRootFilesystem: true
          runAsGroup: 3
          runAsNonRoot: false
          runAsUser: 0
          seLinuxOptions:
            level: ACTOKEY
            role: ACTOKEY
            type: ACTOKEY
            user: ACTOKEY
          seccompProfile:
            localhostProfile: null
            type: ACTOKEY
          windowsOptions:
            gmsaCredentialSpec: ACTOKEY
            gmsaCredentialSpecName: ACTOKEY
            hostProcess: false
            runAsUserName: ACTOKEY
        startupProbe: null
        stdin: false
        stdinOnce: false
        terminationMessagePath: ACTOKEY
        terminationMessagePolicy: ACTOKEY
        tty: false
        volumeDevices:
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        volumeMounts:
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: false
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        workingDir: ACTOKEY
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
