apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 0
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    sidecars:
    - args: null
      command:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      env:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 3
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 2
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      - name: ACTOKEY
        value: null
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef: null
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: '.7157464'
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
      - name: ACTOKEY
        value: null
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: null
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 4
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      envFrom: null
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle: null
      livenessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: null
        grpc:
          port: 1
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 2
        periodSeconds: null
        successThreshold: 2
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        terminationGracePeriodSeconds: 0
        timeoutSeconds: 2
      name: ACTOKEY
      ports:
      - containerPort: 2
        hostIP: null
        hostPort: 2
        name: ACTOKEY
        protocol: ACTOKEY
      - containerPort: 5
        hostIP: ACTOKEY
        hostPort: 2
        name: ACTOKEY
        protocol: ACTOKEY
      - containerPort: 2
        hostIP: null
        hostPort: 3
        name: ACTOKEY
        protocol: ACTOKEY
      readinessProbe:
        exec:
          command: []
        failureThreshold: 2
        grpc:
          port: 4
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 0
        periodSeconds: null
        successThreshold: null
        tcpSocket:
          host: ACTOKEY
          port: 0
        terminationGracePeriodSeconds: 4
        timeoutSeconds: 4
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - ACTOKEY
          drop:
          - ACTOKEY
        privileged: false
        procMount: ACTOKEY
        readOnlyRootFilesystem: false
        runAsGroup: 3
        runAsNonRoot: false
        runAsUser: 1
        seLinuxOptions:
          level: ACTOKEY
          role: ACTOKEY
          type: ACTOKEY
          user: ACTOKEY
        seccompProfile: null
        windowsOptions:
          gmsaCredentialSpec: ACTOKEY
          gmsaCredentialSpecName: ACTOKEY
          hostProcess: true
          runAsUserName: ACTOKEY
      startupProbe:
        exec:
          command:
          - ACTOKEY
        failureThreshold: 3
        grpc:
          port: 2
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: 0
          scheme: ACTOKEY
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        tcpSocket:
          host: ACTOKEY
          port: 4
        terminationGracePeriodSeconds: 3
        timeoutSeconds: 1
      stdin: false
      stdinOnce: false
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: ACTOKEY
      tty: true
      volumeDevices:
      - devicePath: ACTOKEY
        name: ACTOKEY
      volumeMounts:
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: null
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      workingDir: ACTOKEY
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
