apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  adminServerService:
    annotations:
      ACTOKEY: ACTOKEY
    external: true
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  probes:
    readinessProbe:
      initialDelaySeconds: 0
  replicas: 3
  storageType: persistence
