apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: test-cluster
spec:
  configUpdateStrategy: RollingUpdate
  enableDynamicConfiguration: true
  helper:
    image: busybox:1.34.1
  pd:
    baseImage: pingcap/pd
    config: "[dashboard]\n  internal-proxy = true\n"
    maxFailoverCount: 0
    mountClusterClientSecret: true
    replicas: 3
    requests:
      storage: 10Gi
  pvReclaimPolicy: Retain
  tidb:
    additionalVolumes:
    - awsElasticBlockStore:
        fsType: ACTOKEY
        partition: 4
        readOnly: false
        volumeID: ACTOKEY
      azureDisk:
        cachingMode: ACTOKEY
        diskName: ACTOKEY
        diskURI: ACTOKEY
        fsType: ACTOKEY
        kind: ACTOKEY
        readOnly: true
      azureFile:
        readOnly: null
        secretName: ACTOKEY
        shareName: ACTOKEY
      cephfs:
        monitors:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        path: ACTOKEY
        readOnly: false
        secretFile: ACTOKEY
        secretRef: null
        user: null
      cinder:
        fsType: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        volumeID: ACTOKEY
      configMap:
        defaultMode: 4
        items:
        - key: ACTOKEY
          mode: 2
          path: ACTOKEY
        - key: ACTOKEY
          mode: 2
          path: ACTOKEY
        name: null
        optional: true
      csi:
        driver: ACTOKEY
        fsType: ACTOKEY
        nodePublishSecretRef:
          name: ACTOKEY
        readOnly: true
        volumeAttributes:
          ACTOKEY: ACTOKEY
      downwardAPI:
        defaultMode: 0
        items:
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 5
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: '97261494'
            resource: ACTOKEY
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 3
          path: ACTOKEY
          resourceFieldRef:
            containerName: null
            divisor: '+5725893725'
            resource: ACTOKEY
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 0
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 1
            resource: ACTOKEY
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 2
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: null
            resource: ACTOKEY
      emptyDir: null
      ephemeral: null
      fc:
        fsType: ACTOKEY
        lun: 3
        readOnly: true
        targetWWNs: []
        wwids: null
      flexVolume:
        driver: ACTOKEY
        fsType: ACTOKEY
        options:
          ACTOKEY: ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
      flocker:
        datasetName: ACTOKEY
        datasetUUID: ACTOKEY
      gcePersistentDisk:
        fsType: ACTOKEY
        partition: 4
        pdName: ACTOKEY
        readOnly: true
      gitRepo:
        directory: null
        repository: ACTOKEY
        revision: ACTOKEY
      glusterfs: null
      hostPath:
        path: ACTOKEY
        type: ACTOKEY
      iscsi:
        chapAuthDiscovery: null
        chapAuthSession: false
        fsType: ACTOKEY
        initiatorName: ACTOKEY
        iqn: ACTOKEY
        iscsiInterface: ACTOKEY
        lun: 4
        portals: []
        readOnly: false
        secretRef:
          name: ACTOKEY
        targetPortal: ACTOKEY
      name: ACTOKEY
      nfs:
        path: ACTOKEY
        readOnly: null
        server: ACTOKEY
      persistentVolumeClaim:
        claimName: ACTOKEY
        readOnly: true
      photonPersistentDisk:
        fsType: ACTOKEY
        pdID: ACTOKEY
      portworxVolume:
        fsType: ACTOKEY
        readOnly: true
        volumeID: ACTOKEY
      projected:
        defaultMode: 1
        sources:
        - configMap:
            items:
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          downwardAPI:
            items: null
          secret: null
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 0
            path: ACTOKEY
        - configMap:
            items:
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 4
              path: ACTOKEY
            - key: ACTOKEY
              mode: 4
              path: ACTOKEY
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            name: ACTOKEY
            optional: false
          downwardAPI:
            items:
            - fieldRef: null
              mode: 0
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: '.888'
                resource: ACTOKEY
            - fieldRef:
                apiVersion: null
                fieldPath: ACTOKEY
              mode: 5
              path: ACTOKEY
              resourceFieldRef: null
            - fieldRef: null
              mode: 4
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: '78300803.'
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 3
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: 4
                resource: ACTOKEY
          secret:
            items:
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 0
            path: ACTOKEY
        - configMap:
            items:
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          downwardAPI:
            items: []
          secret:
            items:
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 5
            path: ACTOKEY
        - configMap: null
          downwardAPI:
            items:
            - fieldRef: null
              mode: null
              path: ACTOKEY
              resourceFieldRef:
                containerName: null
                divisor: 4
                resource: ACTOKEY
          secret:
            items:
            - key: ACTOKEY
              mode: 1
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            name: ACTOKEY
            optional: null
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 4
            path: ACTOKEY
      quobyte:
        group: ACTOKEY
        readOnly: true
        registry: ACTOKEY
        tenant: ACTOKEY
        user: ACTOKEY
        volume: ACTOKEY
      rbd:
        fsType: ACTOKEY
        image: ACTOKEY
        keyring: ACTOKEY
        monitors:
        - ACTOKEY
        - ACTOKEY
        pool: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      scaleIO:
        fsType: ACTOKEY
        gateway: ACTOKEY
        protectionDomain: ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        sslEnabled: false
        storageMode: ACTOKEY
        storagePool: ACTOKEY
        system: ACTOKEY
        volumeName: ACTOKEY
      secret: null
      storageos:
        fsType: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        volumeName: ACTOKEY
        volumeNamespace: ACTOKEY
      vsphereVolume:
        fsType: ACTOKEY
        storagePolicyID: ACTOKEY
        storagePolicyName: ACTOKEY
        volumePath: ACTOKEY
    baseImage: pingcap/tidb
    config: "[performance]\n  tcp-keep-alive = true\n"
    maxFailoverCount: 0
    replicas: 3
    service:
      externalTrafficPolicy: Local
      type: NodePort
  tikv:
    baseImage: pingcap/tikv
    config: 'log-level = "info"

      '
    maxFailoverCount: 0
    mountClusterClientSecret: true
    recoverFailover: false
    replicas: 3
    requests:
      storage: 100Gi
    separateRaftLog: true
  timezone: UTC
  version: v5.4.0
