apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    sidecarPVCs: []
    sidecarVolumes:
    - awsElasticBlockStore:
        fsType: ACTOKEY
        partition: 0
        readOnly: true
        volumeID: ACTOKEY
      azureDisk:
        cachingMode: ACTOKEY
        diskName: ACTOKEY
        diskURI: ACTOKEY
        fsType: ACTOKEY
        kind: ACTOKEY
        readOnly: true
      azureFile:
        readOnly: true
        secretName: ACTOKEY
        shareName: ACTOKEY
      cephfs:
        monitors:
        - ACTOKEY
        path: ACTOKEY
        readOnly: true
        secretFile: ACTOKEY
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      cinder:
        fsType: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        volumeID: ACTOKEY
      configMap:
        defaultMode: 1
        items:
        - key: ACTOKEY
          mode: 1
          path: ACTOKEY
        - key: ACTOKEY
          mode: 5
          path: ACTOKEY
        - key: ACTOKEY
          mode: 0
          path: ACTOKEY
        - key: ACTOKEY
          mode: null
          path: ACTOKEY
        name: ACTOKEY
        optional: false
      csi:
        driver: ACTOKEY
        fsType: null
        nodePublishSecretRef:
          name: null
        readOnly: true
        volumeAttributes:
          ACTOKEY: ACTOKEY
      downwardAPI:
        defaultMode: null
        items:
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 2
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 4
            resource: ACTOKEY
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 0
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 1
            resource: ACTOKEY
      emptyDir:
        medium: ACTOKEY
        sizeLimit: '23'
      ephemeral:
        volumeClaimTemplate:
          metadata: null
          spec:
            accessModes:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            dataSource:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            dataSourceRef:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            resources: null
            selector:
              matchExpressions:
              - key: ACTOKEY
                operator: ACTOKEY
                values:
                - ACTOKEY
                - ACTOKEY
              - key: ACTOKEY
                operator: ACTOKEY
                values:
                - ACTOKEY
                - ACTOKEY
                - ACTOKEY
              matchLabels:
                ACTOKEY: ACTOKEY
            storageClassName: ACTOKEY
            volumeMode: ACTOKEY
            volumeName: ACTOKEY
      fc:
        fsType: ACTOKEY
        lun: 3
        readOnly: null
        targetWWNs:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        wwids:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
      flexVolume:
        driver: ACTOKEY
        fsType: ACTOKEY
        options:
          ACTOKEY: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
      flocker:
        datasetName: ACTOKEY
        datasetUUID: ACTOKEY
      gcePersistentDisk:
        fsType: ACTOKEY
        partition: 0
        pdName: ACTOKEY
        readOnly: true
      gitRepo:
        directory: ACTOKEY
        repository: ACTOKEY
        revision: ACTOKEY
      glusterfs:
        endpoints: ACTOKEY
        path: ACTOKEY
        readOnly: true
      hostPath:
        path: ACTOKEY
        type: ACTOKEY
      iscsi:
        chapAuthDiscovery: false
        chapAuthSession: true
        fsType: ACTOKEY
        initiatorName: ACTOKEY
        iqn: ACTOKEY
        iscsiInterface: ACTOKEY
        lun: 4
        portals:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        readOnly: true
        secretRef: null
        targetPortal: ACTOKEY
      name: ACTOKEY
      nfs:
        path: ACTOKEY
        readOnly: true
        server: ACTOKEY
      persistentVolumeClaim:
        claimName: ACTOKEY
        readOnly: true
      photonPersistentDisk:
        fsType: ACTOKEY
        pdID: ACTOKEY
      portworxVolume: null
      projected:
        defaultMode: 0
        sources:
        - configMap:
            items:
            - key: ACTOKEY
              mode: null
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            - key: ACTOKEY
              mode: 1
              path: ACTOKEY
            name: null
            optional: false
          downwardAPI:
            items: []
          secret:
            items:
            - key: ACTOKEY
              mode: null
              path: ACTOKEY
            - key: ACTOKEY
              mode: 4
              path: ACTOKEY
            - key: ACTOKEY
              mode: 4
              path: ACTOKEY
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 3
            path: ACTOKEY
        - configMap:
            items:
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            - key: ACTOKEY
              mode: 4
              path: ACTOKEY
            - key: ACTOKEY
              mode: 1
              path: ACTOKEY
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            name: ACTOKEY
            optional: false
          downwardAPI:
            items:
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: null
              path: ACTOKEY
              resourceFieldRef:
                containerName: null
                divisor: '5468191741.'
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 3
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: -.85730147e.1447
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 2
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: 0
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 5
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: 2
                resource: ACTOKEY
          secret:
            items:
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            - key: ACTOKEY
              mode: 1
              path: ACTOKEY
            name: ACTOKEY
            optional: false
          serviceAccountToken: null
        - configMap: null
          downwardAPI:
            items: []
          secret:
            items:
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            - key: ACTOKEY
              mode: 0
              path: ACTOKEY
            name: ACTOKEY
            optional: false
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 4
            path: ACTOKEY
      quobyte:
        group: ACTOKEY
        readOnly: true
        registry: ACTOKEY
        tenant: ACTOKEY
        user: ACTOKEY
        volume: ACTOKEY
      rbd:
        fsType: ACTOKEY
        image: ACTOKEY
        keyring: ACTOKEY
        monitors:
        - ACTOKEY
        pool: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      scaleIO: null
      secret:
        defaultMode: 3
        items: []
        optional: true
        secretName: ACTOKEY
      storageos: null
      vsphereVolume:
        fsType: ACTOKEY
        storagePolicyID: null
        storagePolicyName: ACTOKEY
        volumePath: ACTOKEY
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
