apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: test-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 101m
        memory: 128Mi
      requests:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  redisFollower:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - kind-worker
              - kind-worker2
              - kind-worker3kind-control-plane
    livenessProbe:
      exec:
        command:
        - ACTOKEY
        - ACTOKEY
      failureThreshold: 1
      grpc:
        port: 2
        service: null
      httpGet:
        host: ACTOKEY
        httpHeaders:
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        - name: ACTOKEY
          value: ACTOKEY
        path: ACTOKEY
        port: ACTOKEY
        scheme: ACTOKEY
      initialDelaySeconds: 5
      periodSeconds: 0
      successThreshold: 5
      tcpSocket: null
      terminationGracePeriodSeconds: 3
      timeoutSeconds: 0
    pdb:
      enabled: true
      maxUnavailable: 0
      minAvailable: null
    readinessProbe:
      exec:
        command:
        - ACTOKEY
      failureThreshold: 1
      grpc:
        port: 4
        service: ACTOKEY
      httpGet: null
      initialDelaySeconds: 2
      periodSeconds: 0
      successThreshold: null
      tcpSocket:
        host: null
        port: 3
      terminationGracePeriodSeconds: 2
      timeoutSeconds: 3
    redisConfig:
      additionalRedisConfig: ACTOKEY
    replicas: 0
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
