apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    sidecars:
    - args:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      command:
      - ACTOKEY
      - ACTOKEY
      env:
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 0
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: null
            divisor: 1
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: null
            optional: true
      - name: ACTOKEY
        value: ACTOKEY
        valueFrom:
          configMapKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: false
          fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: +.6136P
            resource: ACTOKEY
          secretKeyRef:
            key: ACTOKEY
            name: ACTOKEY
            optional: true
      envFrom:
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: null
        secretRef:
          name: ACTOKEY
          optional: true
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: true
      - configMapRef:
          name: ACTOKEY
          optional: true
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: false
      - configMapRef:
          name: ACTOKEY
          optional: false
        prefix: ACTOKEY
        secretRef:
          name: ACTOKEY
          optional: true
      image: ACTOKEY
      imagePullPolicy: ACTOKEY
      lifecycle:
        postStart:
          exec: null
          httpGet:
            host: ACTOKEY
            httpHeaders: []
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: 4
        preStop:
          exec:
            command: null
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
      livenessProbe:
        exec:
          command:
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
          - ACTOKEY
        failureThreshold: 3
        grpc:
          port: 3
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders: []
          path: ACTOKEY
          port: 0
          scheme: ACTOKEY
        initialDelaySeconds: 4
        periodSeconds: 1
        successThreshold: 5
        tcpSocket:
          host: ACTOKEY
          port: ACTOKEY
        terminationGracePeriodSeconds: 0
        timeoutSeconds: 3
      name: ACTOKEY
      ports:
      - containerPort: 4
        hostIP: null
        hostPort: null
        name: ACTOKEY
        protocol: ACTOKEY
      - containerPort: 0
        hostIP: ACTOKEY
        hostPort: 1
        name: ACTOKEY
        protocol: ACTOKEY
      readinessProbe: null
      resources:
        limits:
          cpu: 800m
          memory: 1000m
        requests:
          cpu: 800m
          memory: 1000m
      securityContext: null
      startupProbe:
        exec:
          command: null
        failureThreshold: 4
        grpc:
          port: 0
          service: ACTOKEY
        httpGet:
          host: ACTOKEY
          httpHeaders:
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          - name: ACTOKEY
            value: ACTOKEY
          path: ACTOKEY
          port: ACTOKEY
          scheme: ACTOKEY
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 4
        tcpSocket:
          host: ACTOKEY
          port: 3
        terminationGracePeriodSeconds: 1
        timeoutSeconds: 3
      stdin: false
      stdinOnce: true
      terminationMessagePath: ACTOKEY
      terminationMessagePolicy: ACTOKEY
      tty: false
      volumeDevices:
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      - devicePath: ACTOKEY
        name: ACTOKEY
      volumeMounts:
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: true
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: false
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      - mountPath: ACTOKEY
        mountPropagation: ACTOKEY
        name: ACTOKEY
        readOnly: true
        subPath: ACTOKEY
        subPathExpr: ACTOKEY
      workingDir: ACTOKEY
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
