apiVersion: pxc.percona.com/v1-11-0
kind: PerconaXtraDBCluster
metadata:
  finalizers:
  - delete-pxc-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.11.0-pxc8.0-backup
    imagePullPolicy: IfNotPresent
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    schedule:
    - keep: 3
      name: sat-night-backup
      schedule: 0 0 * * 6
      storageName: s3-us-west
    - keep: 5
      name: daily-backup
      schedule: 0 0 * * *
      storageName: fs-pvc
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6G
      s3-us-west:
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
        type: s3
        verifyTLS: true
  crVersion: 1.11.0
  enableCRValidationWebhook: true
  haproxy:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-haproxy
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.11.0-logcollector
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 100M
  pmm:
    enabled: false
    image: percona/pmm-client:2.28.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 300m
        memory: 150M
    serverHost: monitoring-service
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: false
    gracePeriod: 30
    image: percona/percona-xtradb-cluster-operator:1.11.0-proxysql
    imagePullPolicy: IfNotPresent
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    sidecarVolumes:
    - awsElasticBlockStore:
        fsType: ACTOKEY
        partition: 5
        readOnly: true
        volumeID: ACTOKEY
      azureDisk:
        cachingMode: ACTOKEY
        diskName: ACTOKEY
        diskURI: ACTOKEY
        fsType: ACTOKEY
        kind: ACTOKEY
        readOnly: true
      azureFile:
        readOnly: true
        secretName: ACTOKEY
        shareName: ACTOKEY
      cephfs: null
      cinder:
        fsType: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        volumeID: ACTOKEY
      configMap:
        defaultMode: 2
        items:
        - key: ACTOKEY
          mode: 4
          path: ACTOKEY
        name: ACTOKEY
        optional: true
      csi:
        driver: ACTOKEY
        fsType: ACTOKEY
        nodePublishSecretRef:
          name: ACTOKEY
        readOnly: true
        volumeAttributes:
          ACTOKEY: ACTOKEY
      downwardAPI:
        defaultMode: 4
        items:
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 0
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 3
            resource: ACTOKEY
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 5
          path: ACTOKEY
          resourceFieldRef:
            containerName: null
            divisor: .272k
            resource: ACTOKEY
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 3
          path: ACTOKEY
          resourceFieldRef: null
        - fieldRef:
            apiVersion: ACTOKEY
            fieldPath: ACTOKEY
          mode: 4
          path: ACTOKEY
          resourceFieldRef:
            containerName: ACTOKEY
            divisor: 5
            resource: ACTOKEY
      emptyDir:
        medium: ACTOKEY
        sizeLimit: 5
      ephemeral:
        volumeClaimTemplate:
          metadata: null
          spec:
            accessModes:
            - ACTOKEY
            - ACTOKEY
            dataSource:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            dataSourceRef:
              apiGroup: ACTOKEY
              kind: ACTOKEY
              name: ACTOKEY
            resources:
              limits: null
              requests:
                ACTOKEY: 4
            selector: null
            storageClassName: ACTOKEY
            volumeMode: ACTOKEY
            volumeName: ACTOKEY
      fc:
        fsType: ACTOKEY
        lun: 4
        readOnly: false
        targetWWNs:
        - ACTOKEY
        - ACTOKEY
        wwids:
        - ACTOKEY
        - ACTOKEY
      flexVolume:
        driver: ACTOKEY
        fsType: ACTOKEY
        options:
          ACTOKEY: ACTOKEY
        readOnly: false
        secretRef: null
      flocker: null
      gcePersistentDisk:
        fsType: ACTOKEY
        partition: 1
        pdName: ACTOKEY
        readOnly: true
      gitRepo:
        directory: ACTOKEY
        repository: ACTOKEY
        revision: ACTOKEY
      glusterfs:
        endpoints: ACTOKEY
        path: ACTOKEY
        readOnly: false
      hostPath:
        path: ACTOKEY
        type: ACTOKEY
      iscsi:
        chapAuthDiscovery: false
        chapAuthSession: false
        fsType: null
        initiatorName: ACTOKEY
        iqn: ACTOKEY
        iscsiInterface: null
        lun: 4
        portals:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        targetPortal: ACTOKEY
      name: ACTOKEY
      nfs:
        path: ACTOKEY
        readOnly: false
        server: ACTOKEY
      persistentVolumeClaim:
        claimName: ACTOKEY
        readOnly: false
      photonPersistentDisk:
        fsType: ACTOKEY
        pdID: ACTOKEY
      portworxVolume:
        fsType: null
        readOnly: false
        volumeID: ACTOKEY
      projected:
        defaultMode: 2
        sources:
        - configMap: null
          downwardAPI:
            items:
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 1
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: null
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 5
              path: ACTOKEY
              resourceFieldRef: null
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 3
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: 268M
                resource: ACTOKEY
          secret: null
          serviceAccountToken: null
        - configMap:
            items: null
            name: ACTOKEY
            optional: true
          downwardAPI:
            items: null
          secret:
            items: []
            name: ACTOKEY
            optional: false
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: 5
            path: ACTOKEY
        - configMap:
            items:
            - key: ACTOKEY
              mode: null
              path: ACTOKEY
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          downwardAPI:
            items:
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 1
              path: ACTOKEY
              resourceFieldRef: null
            - fieldRef:
                apiVersion: null
                fieldPath: ACTOKEY
              mode: 1
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: null
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 5
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: 4
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 2
              path: ACTOKEY
              resourceFieldRef:
                containerName: null
                divisor: 4
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 3
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: -.21Gi
                resource: ACTOKEY
          secret:
            items:
            - key: ACTOKEY
              mode: null
              path: ACTOKEY
            - key: ACTOKEY
              mode: 4
              path: ACTOKEY
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            name: ACTOKEY
            optional: false
          serviceAccountToken:
            audience: null
            expirationSeconds: 1
            path: ACTOKEY
        - configMap:
            items:
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            name: ACTOKEY
            optional: true
          downwardAPI:
            items:
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 1
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: null
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 1
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: null
                resource: ACTOKEY
            - fieldRef:
                apiVersion: null
                fieldPath: ACTOKEY
              mode: 4
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: null
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 5
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: -205888019Ki
                resource: ACTOKEY
          secret:
            items:
            - key: ACTOKEY
              mode: null
              path: ACTOKEY
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            - key: ACTOKEY
              mode: 5
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            name: ACTOKEY
            optional: false
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: null
            path: ACTOKEY
        - configMap:
            items:
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            - key: ACTOKEY
              mode: 2
              path: ACTOKEY
            - key: ACTOKEY
              mode: 3
              path: ACTOKEY
            name: ACTOKEY
            optional: null
          downwardAPI:
            items:
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: null
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: 2
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 4
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: 36e083868362.787
                resource: ACTOKEY
            - fieldRef:
                apiVersion: null
                fieldPath: ACTOKEY
              mode: 5
              path: ACTOKEY
              resourceFieldRef:
                containerName: ACTOKEY
                divisor: -.6
                resource: ACTOKEY
            - fieldRef:
                apiVersion: ACTOKEY
                fieldPath: ACTOKEY
              mode: 1
              path: ACTOKEY
              resourceFieldRef: null
          secret:
            items: null
            name: ACTOKEY
            optional: false
          serviceAccountToken:
            audience: ACTOKEY
            expirationSeconds: null
            path: ACTOKEY
      quobyte:
        group: ACTOKEY
        readOnly: false
        registry: ACTOKEY
        tenant: ACTOKEY
        user: null
        volume: ACTOKEY
      rbd:
        fsType: ACTOKEY
        image: ACTOKEY
        keyring: ACTOKEY
        monitors: []
        pool: ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        user: ACTOKEY
      scaleIO:
        fsType: ACTOKEY
        gateway: ACTOKEY
        protectionDomain: ACTOKEY
        readOnly: false
        secretRef:
          name: ACTOKEY
        sslEnabled: true
        storageMode: ACTOKEY
        storagePool: null
        system: ACTOKEY
        volumeName: ACTOKEY
      secret:
        defaultMode: 2
        items:
        - key: ACTOKEY
          mode: 2
          path: ACTOKEY
        - key: ACTOKEY
          mode: 3
          path: ACTOKEY
        - key: ACTOKEY
          mode: 0
          path: ACTOKEY
        optional: true
        secretName: ACTOKEY
      storageos:
        fsType: ACTOKEY
        readOnly: true
        secretRef:
          name: ACTOKEY
        volumeName: ACTOKEY
        volumeNamespace: ACTOKEY
      vsphereVolume:
        fsType: null
        storagePolicyID: ACTOKEY
        storagePolicyName: ACTOKEY
        volumePath: ACTOKEY
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    autoRecovery: true
    enabled: true
    gracePeriod: 30
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    imagePullPolicy: IfNotPresent
    livenessDelaySec: 300
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 8.0-recommended
    schedule: 0 4 * * *
    versionServiceEndpoint: https://check.percona.com
