apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  config:
    snapCount: 0
  headlessService:
    annotations:
      ACTOKEY: ACTOKEY
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  replicas: 3
  storageType: persistence
