apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      sidecars:
      - args:
        - ACTOKEY
        - ACTOKEY
        command:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        env:
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef: null
            fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 933Gi
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef: null
            fieldRef: null
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 3
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: true
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef: null
            fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: .757471u
              resource: ACTOKEY
            secretKeyRef: null
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: true
            fieldRef:
              apiVersion: null
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: .937355n
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: true
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
            fieldRef:
              apiVersion: null
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: null
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: null
              optional: false
        envFrom:
        - configMapRef:
            name: ACTOKEY
            optional: false
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: false
        - configMapRef:
            name: ACTOKEY
            optional: false
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: false
        - configMapRef:
            name: ACTOKEY
            optional: true
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: false
        image: ACTOKEY
        imagePullPolicy: null
        lifecycle:
          postStart:
            exec:
              command:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            httpGet:
              host: ACTOKEY
              httpHeaders: null
              path: ACTOKEY
              port: ACTOKEY
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: 0
          preStop:
            exec:
              command: []
            httpGet:
              host: ACTOKEY
              httpHeaders:
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              path: ACTOKEY
              port: ACTOKEY
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: 1
        livenessProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 4
          grpc:
            port: 2
            service: ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: null
            port: ACTOKEY
            scheme: ACTOKEY
          initialDelaySeconds: 3
          periodSeconds: null
          successThreshold: 1
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 0
          timeoutSeconds: 0
        name: ACTOKEY
        ports:
        - containerPort: 4
          hostIP: ACTOKEY
          hostPort: 0
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 2
          hostIP: null
          hostPort: null
          name: ACTOKEY
          protocol: ACTOKEY
        readinessProbe:
          exec:
            command: []
          failureThreshold: 2
          grpc:
            port: 1
            service: ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders: null
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 5
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: null
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 800m
            memory: 1000m
          requests:
            cpu: 800m
            memory: 1000m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ACTOKEY
          privileged: null
          procMount: ACTOKEY
          readOnlyRootFilesystem: null
          runAsGroup: 1
          runAsNonRoot: false
          runAsUser: 2
          seLinuxOptions:
            level: ACTOKEY
            role: ACTOKEY
            type: ACTOKEY
            user: ACTOKEY
          seccompProfile: null
          windowsOptions: null
        startupProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 0
          grpc:
            port: 1
            service: null
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            path: null
            port: 3
            scheme: ACTOKEY
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: null
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 2
          timeoutSeconds: 2
        stdin: null
        stdinOnce: true
        terminationMessagePath: ACTOKEY
        terminationMessagePolicy: ACTOKEY
        tty: false
        volumeDevices: []
        volumeMounts:
        - mountPath: ACTOKEY
          mountPropagation: null
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: null
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: false
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: null
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: false
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        workingDir: ACTOKEY
      - args:
        - ACTOKEY
        command: null
        env:
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
            fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 0
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: null
            fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: -.560934
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: null
              optional: true
        envFrom:
        - configMapRef:
            name: ACTOKEY
            optional: false
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: true
        - configMapRef:
            name: ACTOKEY
            optional: true
          prefix: null
          secretRef:
            name: ACTOKEY
            optional: true
        - configMapRef:
            name: ACTOKEY
            optional: null
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: false
        - configMapRef: null
          prefix: ACTOKEY
          secretRef:
            name: ACTOKEY
            optional: false
        image: ACTOKEY
        imagePullPolicy: ACTOKEY
        lifecycle:
          postStart:
            exec:
              command:
              - ACTOKEY
              - ACTOKEY
            httpGet:
              host: ACTOKEY
              httpHeaders:
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              path: null
              port: 0
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: 0
          preStop:
            exec:
              command:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            httpGet:
              host: ACTOKEY
              httpHeaders:
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              path: ACTOKEY
              port: ACTOKEY
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: ACTOKEY
        livenessProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 2
          grpc:
            port: 5
            service: ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: null
            port: ACTOKEY
            scheme: ACTOKEY
          initialDelaySeconds: 4
          periodSeconds: 5
          successThreshold: 0
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 5
          timeoutSeconds: 2
        name: ACTOKEY
        ports: null
        readinessProbe:
          exec:
            command: null
          failureThreshold: 2
          grpc:
            port: 2
            service: ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders: []
            path: ACTOKEY
            port: ACTOKEY
            scheme: null
          initialDelaySeconds: 0
          periodSeconds: 3
          successThreshold: 3
          tcpSocket:
            host: ACTOKEY
            port: 0
          terminationGracePeriodSeconds: 3
          timeoutSeconds: 0
        resources:
          limits:
            cpu: 800m
            memory: 1000m
          requests:
            cpu: 800m
            memory: 1000m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: null
            drop:
            - ACTOKEY
            - ACTOKEY
          privileged: false
          procMount: ACTOKEY
          readOnlyRootFilesystem: false
          runAsGroup: 1
          runAsNonRoot: false
          runAsUser: 0
          seLinuxOptions:
            level: ACTOKEY
            role: ACTOKEY
            type: ACTOKEY
            user: ACTOKEY
          seccompProfile: null
          windowsOptions:
            gmsaCredentialSpec: ACTOKEY
            gmsaCredentialSpecName: ACTOKEY
            hostProcess: true
            runAsUserName: null
        startupProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 5
          grpc: null
          httpGet:
            host: null
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: 2
            scheme: ACTOKEY
          initialDelaySeconds: null
          periodSeconds: 0
          successThreshold: null
          tcpSocket: null
          terminationGracePeriodSeconds: 0
          timeoutSeconds: 2
        stdin: false
        stdinOnce: false
        terminationMessagePath: ACTOKEY
        terminationMessagePolicy: ACTOKEY
        tty: false
        volumeDevices:
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        volumeMounts:
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: null
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: null
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: false
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: false
          subPath: null
          subPathExpr: ACTOKEY
        workingDir: ACTOKEY
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
