apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  finalizers:
  - delete-psmdb-pods-in-order
  name: test-cluster
spec:
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:1.7.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    serviceAccountName: percona-server-mongodb-operator
    tasks:
    - compressionLevel: 6
      compressionType: gzip
      enabled: true
      keep: 3
      name: daily-s3-us-west
      schedule: 0 0 * * *
      storageName: s3-us-west
  clusterServiceDNSMode: ''
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:4.4.10-11
  imagePullPolicy: IfNotPresent
  multiCluster:
    DNSSuffix: svc.clusterset.local
    enabled: false
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
  replsets:
  - arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: true
      size: 2
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      annotations:
        ACTOKEY: ''
      configuration: "operationProfiling:\n  mode: slowOp\nsystemLog:\n  verbosity:\
        \ 1\n"
      enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      sidecars:
      - args:
        - ACTOKEY
        - ACTOKEY
        - ACTOKEY
        command: []
        env:
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom: null
        - name: ACTOKEY
          value: null
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: null
              optional: true
            fieldRef: null
            resourceFieldRef:
              containerName: null
              divisor: -.10905688
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: true
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: true
            fieldRef: null
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: 5
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
        - name: ACTOKEY
          value: ACTOKEY
          valueFrom:
            configMapKeyRef:
              key: ACTOKEY
              name: null
              optional: true
            fieldRef:
              apiVersion: ACTOKEY
              fieldPath: ACTOKEY
            resourceFieldRef:
              containerName: ACTOKEY
              divisor: null
              resource: ACTOKEY
            secretKeyRef:
              key: ACTOKEY
              name: ACTOKEY
              optional: false
        envFrom: []
        image: ACTOKEY
        imagePullPolicy: ACTOKEY
        lifecycle:
          postStart:
            exec:
              command: []
            httpGet:
              host: ACTOKEY
              httpHeaders:
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              path: ACTOKEY
              port: ACTOKEY
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: ACTOKEY
          preStop:
            exec:
              command:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            httpGet:
              host: ACTOKEY
              httpHeaders:
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              - name: ACTOKEY
                value: ACTOKEY
              path: ACTOKEY
              port: ACTOKEY
              scheme: ACTOKEY
            tcpSocket:
              host: ACTOKEY
              port: 2
        livenessProbe:
          exec:
            command:
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
            - ACTOKEY
          failureThreshold: 1
          grpc:
            port: 4
            service: ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders: []
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 2
          timeoutSeconds: 2
        name: ACTOKEY
        ports:
        - containerPort: 2
          hostIP: null
          hostPort: 2
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 3
          hostIP: ACTOKEY
          hostPort: null
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 2
          hostIP: ACTOKEY
          hostPort: 5
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 2
          hostIP: ACTOKEY
          hostPort: 5
          name: ACTOKEY
          protocol: ACTOKEY
        - containerPort: 5
          hostIP: null
          hostPort: 3
          name: ACTOKEY
          protocol: ACTOKEY
        readinessProbe:
          exec: null
          failureThreshold: 0
          grpc: null
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          initialDelaySeconds: 4
          periodSeconds: 3
          successThreshold: 3
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 2
          timeoutSeconds: null
        resources:
          limits:
            cpu: 800m
            memory: 1000m
          requests:
            cpu: 800m
            memory: 1000m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ACTOKEY
            - ACTOKEY
          privileged: true
          procMount: ACTOKEY
          readOnlyRootFilesystem: false
          runAsGroup: 4
          runAsNonRoot: false
          runAsUser: 3
          seLinuxOptions: null
          seccompProfile:
            localhostProfile: ACTOKEY
            type: ACTOKEY
          windowsOptions:
            gmsaCredentialSpec: ACTOKEY
            gmsaCredentialSpecName: ACTOKEY
            hostProcess: true
            runAsUserName: ACTOKEY
        startupProbe:
          exec: null
          failureThreshold: 2
          grpc:
            port: 0
            service: ACTOKEY
          httpGet:
            host: ACTOKEY
            httpHeaders:
            - name: ACTOKEY
              value: ACTOKEY
            path: ACTOKEY
            port: ACTOKEY
            scheme: ACTOKEY
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 4
          tcpSocket:
            host: ACTOKEY
            port: ACTOKEY
          terminationGracePeriodSeconds: 4
          timeoutSeconds: 4
        stdin: false
        stdinOnce: false
        terminationMessagePath: ACTOKEY
        terminationMessagePolicy: ACTOKEY
        tty: false
        volumeDevices:
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        - devicePath: ACTOKEY
          name: ACTOKEY
        volumeMounts:
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: false
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        - mountPath: ACTOKEY
          mountPropagation: ACTOKEY
          name: ACTOKEY
          readOnly: true
          subPath: ACTOKEY
          subPathExpr: ACTOKEY
        workingDir: ACTOKEY
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: standard
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    size: 2
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
  secrets:
    encryptionKey: my-cluster-name-mongodb-encryption-key
    users: my-cluster-name-secrets
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: true
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        exposeType: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 2
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: 4.4-never
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
