apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: test-cluster
spec:
  image:
    pullPolicy: IfNotPresent
    repository: pravega/zookeeper
    tag: 0.2.14
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard
  replicas: 3
  storageType: persistence
  volumes:
  - awsElasticBlockStore: null
    azureDisk:
      cachingMode: ACTOKEY
      diskName: ACTOKEY
      diskURI: ACTOKEY
      fsType: ACTOKEY
      kind: ACTOKEY
      readOnly: true
    azureFile:
      readOnly: true
      secretName: ACTOKEY
      shareName: ACTOKEY
    cephfs: null
    cinder:
      fsType: ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
      volumeID: ACTOKEY
    configMap:
      defaultMode: 5
      items: null
      name: ACTOKEY
      optional: false
    csi:
      driver: ACTOKEY
      fsType: ACTOKEY
      nodePublishSecretRef:
        name: ACTOKEY
      readOnly: true
      volumeAttributes:
        ACTOKEY: ACTOKEY
    downwardAPI:
      defaultMode: 0
      items:
      - fieldRef: null
        mode: 3
        path: ACTOKEY
        resourceFieldRef:
          containerName: null
          divisor: 13435.918G
          resource: ACTOKEY
      - fieldRef:
          apiVersion: ACTOKEY
          fieldPath: ACTOKEY
        mode: 1
        path: ACTOKEY
        resourceFieldRef:
          containerName: ACTOKEY
          divisor: '0355327708.'
          resource: ACTOKEY
    emptyDir:
      medium: ACTOKEY
      sizeLimit: -.3414Ei
    ephemeral:
      readOnly: true
      volumeClaimTemplate:
        metadata: null
        spec:
          accessModes:
          - ACTOKEY
          - ACTOKEY
          dataSource:
            apiGroup: ACTOKEY
            kind: ACTOKEY
            name: ACTOKEY
          resources:
            limits:
              ACTOKEY: 5
            requests:
              ACTOKEY: 2
          selector:
            matchExpressions:
            - key: ACTOKEY
              operator: ACTOKEY
              values:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            - key: ACTOKEY
              operator: ACTOKEY
              values:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            - key: ACTOKEY
              operator: ACTOKEY
              values:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            - key: ACTOKEY
              operator: ACTOKEY
              values:
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
              - ACTOKEY
            matchLabels:
              ACTOKEY: ACTOKEY
          storageClassName: ACTOKEY
          volumeMode: ACTOKEY
          volumeName: ACTOKEY
    fc:
      fsType: ACTOKEY
      lun: 1
      readOnly: true
      targetWWNs:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      wwids:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
    flexVolume:
      driver: ACTOKEY
      fsType: ACTOKEY
      options:
        ACTOKEY: ACTOKEY
      readOnly: false
      secretRef:
        name: ACTOKEY
    flocker:
      datasetName: null
      datasetUUID: ACTOKEY
    gcePersistentDisk:
      fsType: ACTOKEY
      partition: 5
      pdName: ACTOKEY
      readOnly: true
    gitRepo: null
    glusterfs:
      endpoints: ACTOKEY
      path: ACTOKEY
      readOnly: true
    hostPath:
      path: ACTOKEY
      type: ACTOKEY
    iscsi:
      chapAuthDiscovery: true
      chapAuthSession: true
      fsType: ACTOKEY
      initiatorName: ACTOKEY
      iqn: ACTOKEY
      iscsiInterface: ACTOKEY
      lun: 3
      portals: []
      readOnly: false
      secretRef:
        name: null
      targetPortal: ACTOKEY
    name: ACTOKEY
    nfs:
      path: ACTOKEY
      readOnly: false
      server: ACTOKEY
    persistentVolumeClaim: null
    photonPersistentDisk:
      fsType: ACTOKEY
      pdID: ACTOKEY
    portworxVolume:
      fsType: ACTOKEY
      readOnly: false
      volumeID: ACTOKEY
    projected:
      defaultMode: 0
      sources:
      - configMap: null
        downwardAPI:
          items: null
        secret:
          items:
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 5
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 2
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          name: null
          optional: true
        downwardAPI: null
        secret:
          items:
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 0
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        downwardAPI: null
        secret:
          items:
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 3
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        serviceAccountToken:
          audience: ACTOKEY
          expirationSeconds: 4
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          name: ACTOKEY
          optional: true
        downwardAPI: null
        secret:
          items:
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: null
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 2
            path: ACTOKEY
          - key: ACTOKEY
            mode: 1
            path: ACTOKEY
          name: ACTOKEY
          optional: false
        serviceAccountToken:
          audience: null
          expirationSeconds: 3
          path: ACTOKEY
      - configMap:
          items:
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 0
            path: ACTOKEY
          - key: ACTOKEY
            mode: 4
            path: ACTOKEY
          name: ACTOKEY
          optional: null
        downwardAPI:
          items: []
        secret:
          items: null
          name: null
          optional: false
        serviceAccountToken: null
    quobyte:
      group: ACTOKEY
      readOnly: true
      registry: ACTOKEY
      tenant: ACTOKEY
      user: ACTOKEY
      volume: ACTOKEY
    rbd:
      fsType: ACTOKEY
      image: ACTOKEY
      keyring: ACTOKEY
      monitors:
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      - ACTOKEY
      pool: ACTOKEY
      readOnly: true
      secretRef:
        name: ACTOKEY
      user: ACTOKEY
    scaleIO: null
    secret:
      defaultMode: 0
      items:
      - key: ACTOKEY
        mode: 5
        path: ACTOKEY
      - key: ACTOKEY
        mode: 3
        path: ACTOKEY
      - key: ACTOKEY
        mode: 4
        path: ACTOKEY
      optional: true
      secretName: ACTOKEY
    storageos:
      fsType: ACTOKEY
      readOnly: true
      secretRef:
        name: ACTOKEY
      volumeName: ACTOKEY
      volumeNamespace: ACTOKEY
    vsphereVolume:
      fsType: ACTOKEY
      storagePolicyID: ACTOKEY
      storagePolicyName: null
      volumePath: ACTOKEY
