apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: test-cluster
spec:
  additionalLabels:
    crdb: is-cool
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v21.2.10
  nodes: 3
  podEnvVariables:
  - name: ACTOKEY
    valueFrom:
      configMapKeyRef:
        key: ACTOKEY
        name: null
        optional: false
      fieldRef:
        apiVersion: ACTOKEY
        fieldPath: ACTOKEY
      resourceFieldRef:
        containerName: ACTOKEY
        divisor: 3
        resource: ACTOKEY
      secretKeyRef:
        key: ACTOKEY
        name: ACTOKEY
        optional: false
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  tlsEnabled: true
